### ISSUE TITLE
Suggestion: historical price minimum and 25-st percentile in the tooltip optionally

### ISSUE THREAD

**Issue by theoden-dd** [shirsig/aux-addon#100]
Rationale: it'll help to estimate how close to the market bottom current price is. So you can decide should you buy that *rigth now* or could you play with bidding at 30m.

However I'm not sure that everyone can make use of it.
So let it be disabled by default, available through commands like "/aux tooltip min", "/aux tooltip q1"

**Comment by shirsig** [comment]
overly complicated, will more likely make the tooltip simpler than more complex
