### ISSUE TITLE
Aux historical value disappears suddenly

### ISSUE THREAD

**Issue by eagle132** [shirsig/aux-addon#103]
I have noticed that about once a month, I will hover over an item to check it's value on the AH (I do a full scan of the AH every few days and a scan of rare+ daily) and all items will have a value of ?. It seems as though all of the saved data wipes itself every couple weeks.

Do you know a reason this might be happening?

**Comment by shirsig** [comment]
Old version, not properly installed/updated, you updated and the update had an incompatible history, you accidentally deleted the savedvariable file ...

**Comment by eagle132** [comment]
All seem to be viable reasons though from my experience it seems to happen at random when I have not touched any addon files in the past several weeks.

Thanks for the response I will keep an eye on it I suppose!
