### ISSUE TITLE
Suggestion: Bid alarm timer

### ISSUE THREAD

**Issue by goudekid** [shirsig/aux-addon#108]
It'd be nice to be able to shift right click an auction and have an alarm set for a time when the auction may be nearing it's end- something like if the text says 24h (which is really just anything greater than 8 hours) it sets an alarm that goes of in 7 hours 55 min (so worst case, you get to the auction and it has about 5 minutes left to go. Likewise for an 8h you'd set it for 1 hr 55 min because 8 hr is just 2-7.99 hrs

Would be really useful to win bids on items with no buyouts or with people who put items up with a 1c bid

**Comment by shirsig** [comment]
Don't really see a compelling reason why this would have to be part of aux. Seems like a better fit for a timer addon of sorts or just a whole independent addon.
