### ISSUE TITLE
[TBC] Search lua error

### ISSUE THREAD

**Issue by QuadrozZz** [shirsig/aux-addon#109]
```
12:05 1. aux-addon\util\info.lua:127: attempt to index local 'item_info' (a nil value)
aux-addon\core\scan.lua:138: in function <Interface\AddOns\aux-addon\core\scan.lua:125>
(tail call): ?:
(tail call): ?:
(tail call): ?:
(tail call): ?:
(tail call): ?:
(tail call): ?:
(tail call): ?:
(tail call): ?:
aux-addon\control.lua:44: in function <Interface\AddOns\aux-addon\control.lua:26>
```

When pressing the search button

**Comment by shirsig** [comment]
hm, I'm not getting this error. have you tried disabling other addons?

**Comment by QuadrozZz** [comment]
http://imgur.com/97UyAOX
all other addons disabled.

**Comment by shirsig** [comment]
have you tried more specific queries? do you always get the error?
on medivh search works fine for me: [](http://i.imgur.com/UMcUofE.png)

**Comment by QuadrozZz** [comment]
Maybe this is somehow related to the fact that:

> The realm will be progression based, emulating the 2.1 patch on the beginning, with all respective attunements.

http://forum.warmane.com/showthread.php?t=352288

**Comment by shirsig** [comment]
no idea, but I'm in the queue, will find out eventually

**Comment by QuadrozZz** [comment]
I tried searching for each section, but stacking just on Weapons and Armors.

**Comment by shirsig** [comment]
should be fixed now, was an itemlink format issue

**Comment by QuadrozZz** [comment]
fixed.
