### ISSUE TITLE
[TBC] Auction duration

### ISSUE THREAD

**Issue by QuadrozZz** [shirsig/aux-addon#110]
Oldest auction duration 2h, 8h, 24h. Cant posting items. Can post just on 24h.
Must be 12h, 24h, 48h.

**Comment by shirsig** [comment]
just fixed this, test please

**Comment by QuadrozZz** [comment]
Can't post auctions for any durations. But text fixed

**Comment by shirsig** [comment]
does it work now?

**Comment by QuadrozZz** [comment]
Nope.

**Comment by shirsig** [comment]
oh, just forgot to remove a broken debug print. now it should work

**Comment by QuadrozZz** [comment]
and text, now 8 hours, need 12 hours. my bad.

**Comment by shirsig** [comment]
hope I got it all right now, including the text in the listings

**Comment by QuadrozZz** [comment]
Yeah, working perfectly.
