### ISSUE TITLE
Bug : incompatibility with Cdframes

### ISSUE THREAD

**Issue by Bifidus** [shirsig/aux-addon#114]
http://imgur.com/a/qpYMo

100% reproductible, whenever i mouseover an item, or open the AH (which i can't use).
The weird thing is "cooldown", the exact same addon "cdframes" was, did not have this issue.

**Comment by shirsig** [comment]
I assume you need to install the newest version of both.

**Comment by Bifidus** [comment]
Right, shame on me, i missed an update somewhere. How can i avoid that ? I check github everyday, but is there a way to subscribe not to all notifications, but only to the new releases ?

**Comment by shirsig** [comment]
Not sure but I don't really play anymore and also gonna be more busy so there likely won't be any major updates breaking compatibility between them anymore.
