### ISSUE TITLE
Bug: bid price displayed incorrectly

### ISSUE THREAD

**Issue by Bifidus** [shirsig/aux-addon#115]
In the "post" tab, the only way to have a correct display of the bid price is to put the slides on "1 stack" AND "1 stack count".
Everytime you change these slides, the bid prices go vastly inferior to the real prices (it's only display, it don't seem to affect the real prices).
Also, these slides never stay in place, you have to put them back for each selling, which is annoying. They always go to maximum value. Can we keep the previous behavior (keep the last position of an actual selling) ?

**Comment by shirsig** [comment]
It's not supposed to show the bids, it's showing what you're actually undercutting. Bid undercutting is only useful for undercutting the stack price (because that controls the position in the default AH listing). If you have a high stick size you need to go much lower.
