### ISSUE TITLE
-dev bugs found

### ISSUE THREAD

**Issue by cnolimes** [shirsig/aux-addon#118]
Hey, Bit! Long time haven't checked your hub as I was playing TBC only and left vanilla. Decided to check you out and found that you've finally made that 20400 comp. Can't express my gratitude enough!!!!!!!!

Been using it for ~24 hours and the bugs I've found so far are:

-- searching with <> filter or an empty search shows only poor/gray quality items

-- rightclicking/dropping item from the bag in the Post tab doesn't do anything.

-- rightclicking an item in the bag doesn't start a Search for that exact item

-- Level range in the Filter Builder doesn't allow to enter higher number than 60 (e.g. 61-70)

Edit:

-- Minimum Quality option in Filter Builder shows the items from the quality I've entered. (e.g. Min. Quality "Poor" will only show Poor items in the results), might be server bug as well. Playing on Medivh

**Comment by Monteo** [comment]
add
2click tabs Auctions 
[00:53] Interface\AddOns\aux-addon\core\scan.lua:136: attempt to compare nil with number

**Comment by shirsig** [comment]
- the <> filter bug I cannot reproduce
- The dropping I believe was removed a while ago because it has no advantage over right click
- Right click was disabled for the time being because the implementation doesn't work in TBC
- Fixed the level range issue.
- quality thing must be a server bug, also happens in the default AH


> 2click tabs Auctions
Not sure what that means, you got the newest version/deleted savedvars?

**Comment by Monteo** [comment]
<> Search only 3 pages
Full scan do "percent/70"

**Comment by shirsig** [comment]
<> search scans everything for me

**Comment by cnolimes** [comment]
Thanks for the fixes, Bit!

Found another one, the disenchant values are unavailable for Outland content items.

**Comment by shirsig** [comment]
That's not really a bug, just haven't extended the table for tbc (tbh not sure how it works, in vanilla it could be inferred from level requirements)

**Comment by cnolimes** [comment]
Using iLvl instead of level requirements, here you can find all the info: http://wow.gamepedia.com/index.php?title=Disenchanting_tables&oldid=1279930. The link I'm providing is from 25th of March 2008. You can check the history tab aswell.

**Comment by cnolimes** [comment]
Found another one

<> search works properly after savedvariables clear, might be breaking from visiting neutral AHs.

armor/misc./finger filter doesn't search for fingers but for items from other slots.
The same goes for armor/cloth/back.

Regards.

**Comment by shirsig** [comment]
fixed the queries for inventory slots
sure the <> bug wasn't just happening once (due to a broken older version corruping savedvariables or something)

**Comment by shirsig** [comment]
aux for TBC is now in a separate repo: https://github.com/shirsig/aux-addon-TBC

**Comment by tylercentral** [comment]
I'm able to reproduce the <> grey items bug, after my first initial <> scan, which did in fact scan all pages, any subsequent scan only shows grey items. Has happened twice, not sure what may be corrupting the saved variables.
