### ISSUE TITLE
Post has become worse

### ISSUE THREAD

**Issue by 0ldi** [shirsig/aux-addon#119]
Why was the Bid-list of prices removed from the Post-tab?
How can I now set the starting price in one click, if I do not see the starting prices?
Why is the starting price equal to Buyout?
Why is this done at all?
![](http://imagehost.spark-media.ru/iu/AC/1A/AC1AF737-6CB1-88F9-14C8-036E87864F5F.png)

**Comment by shirsig** [comment]
Simplicity/people requested it. The bid price really only matters when you wanna undercut bid stacks so you're above others in the blizzard ah. There's still a bid listing you can get with /aux post bid (and /run ReloadUI()). It's not strictly a price listing though but optimized for undercutting stack prices, shows the other auctions sorted in descending order by stack price and normalized by your current stack size selection.

**Comment by 0ldi** [comment]
Oops, I'm sorry. I used /aux post bid, but it did not work without /run ReloadUI(). I think you should add to the description to avoid misunderstanding.
Its OK now.

**Comment by shirsig** [comment]
I'm just gonna make it not require a reload when I have time sometime.

**Comment by 0ldi** [comment]
Oops, not OK.
Why does the price per 1 item decrease with the increase in the number of items? It's definitely broken here :(
https://youtu.be/QnIi9ODLLJI

**Comment by shirsig** [comment]
I just explained it, it's not a price listing, it's stack prices normalized by your stack size selection.

**Comment by 0ldi** [comment]
No idea how to use current system. Earlier, I just clicked 2 times, the top line of Bid and the top line of Buyout, and quickly got the best prices with a minimum undercutting. Now I can not do this... We'll have to look for the old version, before this "innovation."

**Comment by shirsig** [comment]
There's no point in undercutting the unit bid price (in vanilla at least). The only reason to undercut bids is to undercut the stack prices so you'll appear higher up in the default ah which sorts by stack bid price. The listing is sorted in ascending order by stack price and clicking an entry gives you the largest unit price possible that will still undercut the stack price given your current stack size.

**Comment by 0ldi** [comment]
> There's no point in undercutting the unit bid price (in vanilla at least).

I do not know how you make such conclusions. The difference between Bid & Buyout prices for some products can be significant, and people do not buyout what to save money. Bid price is important, and sellers compete among themselves, so the old system clearly showed all Bid prices, and it was easy to put a minimum, and have a better chance of buying your product ...

**Comment by shirsig** [comment]
If you make your bid so high you can only expect one bid you might as well stick with buyout. If you expect multiple people to outbid each other there is little point in undercutting because after the first bid you won't be the lowest anymore anyway.
