### ISSUE TITLE
Speed up scanning, Show estimated time remaining.

### ISSUE THREAD

**Issue by l1amm** [shirsig/aux-addon#121]
Just curious if there is any way to speed up a full scan of the AH... (besides aux ignore owner)
Maybe run multiple scans at once (if thats even possible)

Also would be really nice to show estimated time remaining until scan is complete.

Great addon though!

**Comment by shirsig** [comment]
Not possible. Time indicator would be somewhat unreliable and after a few scans you know how long it takes/can derive the remaining time from the page number anyway.
