### ISSUE TITLE
Suggestion: Make Vendor Sell price use the GetItemInfo()

### ISSUE THREAD

**Issue by Jakobud** [shirsig/aux-addon#126]
Right now, when you use `/aux tooltip merchant sell on` the value is a `?` for anything until you visit a vendor to find out the value.

Why don't you use the API `GetItemInfo()` because it returns the vendor price for every item.

**Comment by shirsig** [comment]
Because it doesn't in vanilla.

**Comment by Jakobud** [comment]
Are you sure? The vanilla addon "Informant" tells you the vendor buy and sell price for everything in the tooltip.

**Comment by shirsig** [comment]
Using its own database just like the one you can get for aux.

**Comment by Jakobud** [comment]
Ah okay. Where can I get this database for aux?

**Comment by Jakobud** [comment]
Found it nevermind. Thanks!
