### ISSUE TITLE
Today's update causes error from crafting.lua:14 attempt to call table value

### ISSUE THREAD

**Issue by AriinPHD** [shirsig/aux-addon#128]
Hey, today's update is causing an error from \core\crafting.lua: 14 attempt to call a table value.

Clean instance: deleted WTF and addon/aux-addon folders before update.

![wow-aux-error_crafting lua 14_atc-tablval](https://user-images.githubusercontent.com/5846389/32297541-c26b986e-bf4f-11e7-95f3-ad29ef3c092c.png)

**Comment by shirsig** [comment]
thanks, should be fixed.
