### ISSUE TITLE
Error when using filter search

### ISSUE THREAD

**Issue by moootv** [shirsig/aux-addon#130]
https://gyazo.com/91fbbbbd8511f8412328c188e854a2c9

Newest version. Worked in the version before. Filter:

plaguebloom/exact/or/percent/100/and/bid-percent/80/left/30m;arthas' tears/exact/or/percent/100/and/bid-percent/80/left/30m;black lotus/exact/or/percent/100/and/bid-percent/80/left/30m;blasted boar lung/exact/or/percent/100/and/bid-percent/80/left/30m;blindweed/exact/or/percent/100/and/bid-percent/80/left/30m;blue power crystal/exact/or/percent/100/and/bid-percent/80/left/30m;briarthorn/exact/or/percent/100/and/bid-percent/80/left/30m;bruiseweed/exact/or/percent/100/and/bid-percent/80/left/30m;chimaerok tenderloin/exact/or/percent/100/and/bid-percent/80/left/30m;deeprock salt/exact/or/percent/100/and/bid-percent/80/left/30m;dense stone/exact/or/percent/100/and/bid-percent/80/left/30m;dream dust/exact/or/percent/100/and/bid-percent/80/left/30m;dreamfoil/exact/or/percent/100/and/bid-percent/80/left/30m;elemental earth/exact/or/percent/100/and/bid-percent/80/left/30m;elemental fire/exact/or/percent/100/and/bid-percent/80/left/30m;elemental water/exact/or/percent/100/and/bid-percent/80/left/30m;fadeleaf/exact/or/percent/100/and/bid-percent/80/left/30m;firebloom/exact/or/percent/100/and/bid-percent/80/left/30m;frostmaul e'ko/exact/or/percent/100/and/bid-percent/80/left/30m;frostsaber e'ko/exact/or/percent/100/and/bid-percent/80/left/30m;ghost mushroom/exact/or/percent/100/and/bid-percent/80/left/30m;golden sansam/exact/or/percent/100/and/bid-percent/80/left/30m;goldthorn/exact/or/percent/100/and/bid-percent/80/left/30m;grave moss/exact/or/percent/100/and/bid-percent/80/left/30m;gromsblood/exact/or/percent/100/and/bid-percent/80/left/30m;heart of the wild/exact/or/percent/100/and/bid-percent/80/left/30m;icecap/exact/or/percent/100/and/bid-percent/80/left/30m;khadgar's whisker/exact/or/percent/100/and/bid-percent/80/left/30m;large venom sac/exact/or/percent/100/and/bid-percent/80/left/30m;mountain silversage/exact/or/percent/100/and/bid-percent/80/left/30m;oily blackmouth/exact/or/percent/100/and/bid-percent/80/left/30m;plagebloom/exact/or/percent/100/and/bid-percent/80/left/30m;red power crystal/exact/or/percent/100/and/bid-percent/80/left/30m;runecloth/exact/or/percent/100/and/bid-percent/80/left/30m;sandworm meat/exact/or/percent/100/and/bid-percent/80/left/30m;scorpok pincer/exact/or/percent/100/and/bid-percent/80/left/30m;snickerfang jowl/exact/or/percent/100/and/bid-percent/80/left/30m;stonescale eel/exact/or/percent/100/and/bid-percent/80/left/30m;stranglekelp/exact/or/percent/100/and/bid-percent/80/left/30m;sungrass/exact/or/percent/100/and/bid-percent/80/left/30m;swiftthistle/exact/or/percent/100/and/bid-percent/80/left/30m;thorium bar/exact/or/percent/100/and/bid-percent/80/left/30m;thorium ore/exact/or/percent/100/and/bid-percent/80/left/30m;vulture gizzard/exact/or/percent/100/and/bid-percent/80/left/30m;winter squid/exact/or/percent/100/and/bid-percent/80/left/30m;winterfall e'ko/exact/or/percent/100/and/bid-percent/80/left/30m;wintersbite/exact/or/percent/100/and/bid-percent/80/left/30m;yellow power crystal/exact/or/percent/100/and/bid-percent/80/left/30m;elemental sharpening stone/exact/or/percent/100/and/bid-percent/80/left/30m;elixir of poison resistance/exact/or/percent/100/and/bid-percent/80/left/30m;elixir of the mongoose/exact/or/percent/100/and/bid-percent/80/left/30m;greater arcane protection potion/exact/or/percent/100/and/bid-percent/80/left/30m;greater fire protection potion/exact/or/percent/100/and/bid-percent/80/left/30m;greater nature protection potion/exact/or/percent/100/and/bid-percent/80/left/30m;greater shadow protection potion/exact/or/percent/100/and/bid-percent/80/left/30m;heavy runecloth bandage/exact/or/percent/100/and/bid-percent/80/left/30m;mighty rage potion/exact/or/percent/100/and/bid-percent/80/left/30m;sheen of zanza/exact/or/percent/100/and/bid-percent/80/left/30m;smoked desert dumplings/exact/or/percent/100/and/bid-percent/80/left/30m;thistle tea/exact/or/percent/100/and/bid-percent/80/left/30m;winterfall firewater/exact/or/percent/100/and/bid-percent/80/left/30m;elixir of the giants/exact/or/percent/100/and/bid-percent/80/left/30m;free action potion/exact/or/percent/100/and/bid-percent/80/left/30m;crystal charge/exact/or/percent/100/and/bid-percent/80/left/30m;crystal yield/exact/or/percent/100/and/bid-percent/80/left/30m;flask of the titans/exact/or/percent/100/and/bid-percent/80/left/30m;greater frost protection potion/exact/or/percent/100/and/bid-percent/80/left/30m;juju flurry/exact/or/percent/100/and/bid-percent/80/left/30m;limited invulnerability potion/exact/or/percent/100/and/bid-percent/80/left/30m;oil of immolation/exact/or/percent/100/and/bid-percent/80/left/30m;restorative potion/exact/or/percent/100/and/bid-percent/80/left/30m;spirit of zanza/exact/or/percent/100/and/bid-percent/80/left/30m;swiftness of zanza/exact/or/percent/100/and/bid-percent/80/left/30m;swiftness potion/exact/or/percent/100/and/bid-percent/80/left/30m;dirge's kickin' chimaerok chops/exact/or/percent/100/and/bid-percent/80/left/30m;frost oil/exact/or/percent/100/and/bid-percent/80/left/30m;gift of arthas/exact/or/percent/100/and/bid-percent/80/left/30m;major healing potion/exact/or/percent/100/and/bid-percent/80/left/30m;blessed sunfruit/exact/or/percent/100/and/bid-percent/80/left/30m;invisibility potion/exact/or/percent/100/and/bid-percent/80/left/30m;living action potion/exact/or/percent/100/and/bid-percent/80/left/30m;stratholme holy water/exact/or/percent/100/and/bid-percent/80/left/30m;thorium grenade/exact/or/percent/100/and/bid-percent/80/left/30m;grilled squid/exact/or/percent/100/and/bid-percent/80/left/30m;savage frond/exact/or/percent/100/and/bid-percent/80/left/30m;crypt fiend parts/exact/or/percent/100/and/bid-percent/80/left/30m;runecloth bag/exact/or/percent/100/and/bid-percent/80/left/30m;righteous orb/exact/or/percent/100/and/bid-percent/80/left/30m;Large Brilliant Shard/exact/or/percent/100/and/bid-percent/80/left/30m

**Comment by shirsig** [comment]
fixed, thanks.
