### ISSUE TITLE
Bug when overing quest items in quest panel

### ISSUE THREAD

**Issue by Altoholic** [shirsig/aux-addon#134]
https://imgur.com/a/TzPyb

**Comment by shirsig** [comment]
This is reproducible or just happened once? Conflict with other addon?

**Comment by Bifidus** [comment]
100% reproducible.
I'll try with no other addon asap.

**Comment by Bifidus** [comment]
https://imgur.com/a/sHdu1

More info avaible this time (the quest, and the item inside that provoque the bug when overing it).

**Comment by shirsig** [comment]
Hm, so did you try with other addons disabled? because this looks a lot like a hook conflict on that function.

**Comment by Bifidus** [comment]
I forget that part, my bad.
And i handed the quest... i'll give it another try with the next occurence of the bug.

**Comment by Bifidus** [comment]
https://imgur.com/a/Nav29

I then disabled all addons except aux : no bug.
I re enabled slowly my addons, a few at a time : no bug.
I enabled all my addons : no bug.
So it's not a 100% reproducible bug, after all...

**Comment by Bifidus** [comment]
https://imgur.com/a/AmzBi

Same scenario, same result.
My guess is login/logout "kills" the bug... until the next time.

**Comment by shirsig** [comment]
Ok, but again :) I need to know which other addon causes it.

**Comment by Bifidus** [comment]
I understand, but i don't see a way to find it, as for enabling/disabling addons, i must logout, which make the bug disappear.
Maybe if i install another addon to manage other addons ingame...

**Comment by shirsig** [comment]
They still require you to reload the ui which would probably have the same effect. However, unless you have a million addons it should be fairly simple to identify a few good candidates for conflicts (like those that have something to do with the quest log, the most obvious being the one that causes the clearly non blizzlike questlog look in your image)

**Comment by Bifidus** [comment]
Sure, it's EQL3, from Laytya. But as i can't reproduce the bug reliably, i suppose you have to look in EQL3 code ?
Here are my addons ::
ActionButtonUtils
addons.txt
AutoBar
Automaton
aux-addon
aux_merchant_prices
Bagnon
Bagnon_Core
Bagnon_Forever
Bagnon_Options
Banknon
BattleShoutGlow
BearCastBar
BetterCharacterStats
Blizzard_AuctionUI
Blizzard_BattlefieldMinimap
Blizzard_BindingUI
Blizzard_CombatText
Blizzard_CraftUI
Blizzard_GMSurveyUI
Blizzard_InspectUI
Blizzard_MacroUI
Blizzard_RaidUI
Blizzard_TalentUI
Blizzard_TradeSkillUI
Blizzard_TrainerUI
BuyEmAll
Cartographer
ccwatch
cdframes
CharactersViewer
ClassicSnowFall
crafty
DebuffTimers
Decursive
DeuceCommander
DoctorDruid
EQCompare
EQL3
Fizzle
FlightMap
FuBar
FuBar_BagFu
FuBar_ClockFu
FuBar_DuraTek
FuBar_FriendsFu
FuBar_GuildFu
FuBar_InstanceResetFu
FuBar_LocationFu
FuBar_MoneyFu
FuBar_PerformanceFu
Ignoreplayer
Lern2Spell
LunaUnitFrames
modtip
MrPlow
!OmniCC
Outfitter
PicoPoisons
postal
Prat-V
QuickBind
retarget
ShaguPlates
simpleMinimap
SmartLoot
sQMinimapFix
!toggle
TrinketMenu
YaHT

**Comment by shirsig** [comment]
I meant a good candidate to disable and check if it still happens.
