### ISSUE TITLE
Suggestion: Option to disable displaying fractions of copper

### ISSUE THREAD

**Issue by ShaunDreclin** [shirsig/aux-addon#136]
It just adds clutter/reduces readability imo.

I don't think I've ever needed to know if something is 50.001 copper per item vs 50 copper per item

Alternative would be to only show fractions of copper where there are any, rather than displaying .000 on whole numbers

**Comment by shirsig** [comment]
The reason was so you can always undercut by 1 copper for the stack. This has actually been removed a while ago already. Prices can still be fractional when you enter them as such or use the automatic undercutting  but it's not shown anymore.

**Comment by ShaunDreclin** [comment]
Oh my bad, I must have an older version of the addon. Thanks!
