### ISSUE TITLE
Suggestion: Allow number ranges when specifying additional filters in the filter builder

### ISSUE THREAD

**Issue by Doctor-Propain** [shirsig/aux-addon#137]
On my server currently, there are ~70 pages of auctions for illusion dust, which means that ~30 pages are not being displayed in the table. (And, unfortunately, only the highest priced auctions got put in the table.) To narrow down the search, I am trying to use the percent filter, but it doesn't allow me to specify a range. Instead, I have to enter each integer individually. The search string ends up looking something like this for a range between 95-105:

Illusion Dust/percent/95/or/percent/96/or/percent/97/or/percent/98/or/percent/99/or/percent/100/or/percent/101/or/percent/102/or/percent/103/or/percent/104/or/percent/105

It would be nice if I could instead specify a range of values in this way:

Illusion Dust/percent/95-105

**Comment by shirsig** [comment]
Percentage filters let through all percentages that are lesser or equal. I see no reason to have a lower bound but if you really want to you could do not/percentage/49/percentage/80 to get results from 50 to 80%

**Comment by shirsig** [comment]
*percent (cabt edit on the phone)

**Comment by Doctor-Propain** [comment]
Alright thanks for responding. I guess I misunderstood the filter as being "exact" when in fact it's "less than or equal to."
