### ISSUE TITLE
Suggestion: Print mail to chat - similar to TSM

### ISSUE THREAD

**Issue by Temporoary** [shirsig/aux-addon#138]
Would it be possible to add the option to print mail contents/sales/bids/gold to the chat box in a similar to retail TSM.  
This makes it easier to quickly view the result of your auctions & bids, especially effective when using an "open all " addon to open a large amount of mail

I've included an example screenshot.

![post](https://user-images.githubusercontent.com/33966667/33222343-63bee166-d14e-11e7-8bb5-e8c80dcece95.png)

**Comment by shirsig** [comment]
No. No point in adding this to aux as there is no connection to the ah, it's purely a mail addon.

**Comment by Temporoary** [comment]
That is a fair point.
You also develop Mail, would it be more suitable to repost this suggestion there or is the answer the same?

**Comment by shirsig** [comment]
It's more suitable but I'm not interested.

**Comment by Temporoary** [comment]
Understood, thanks for your response.
