### ISSUE TITLE
Twilight Cultist Mantle, Robe and Cowl can't be disenchanted

### ISSUE THREAD

**Issue by Ecoround** [shirsig/aux-addon#139]
The Twilight Cultist Mantle, Robe and Cowl (Item ids: 20406, 20407, 20408) can't be disenchanted even though aux lists the disenchant mats in the tooltip of the item. 

Tested on Light's Hope which runs Vanilla 1.12.1

**Comment by shirsig** [comment]
https://github.com/shirsig/aux-addon/issues/116
