### ISSUE TITLE
vendor price filter

### ISSUE THREAD

**Issue by VelixTrebor** [shirsig/aux-addon#140]
Is it possible to build a filter to compare bid/buyout price vs. vendor price? 

Additionally, is it possible add vendor price for all items automatically rather than collection? Informant contains these values and does this currently. I'm not sure if it would be easier to import the information into Aux or to just let Aux call to Informant. 

Please let me know if one of both of these can be done currently.

**Comment by shirsig** [comment]
The filter is vendor-profit/bid-vendor-profit

https://github.com/shirsig/aux_merchant_prices for the price database
