### ISSUE TITLE
Lua error 178

### ISSUE THREAD

**Issue by liskamic** [shirsig/aux-addon#142]
I get the following error message:
Interface\AddOns\aux-addon\core\cache.lua: 178: attempt to index global `aux_item_ids' (a nil value)
The addon is unusable.
I tried disabling all other addons and deleting WDB folder.

**Comment by shirsig** [comment]
Newest version? Client closed when deleting the folder?

**Comment by liskamic** [comment]
Yes to both. I just downloaded it today from here.
Older version caused a different lua error.

**Comment by shirsig** [comment]
also got an error after deleting the savedvariables, but a different one. fixed it now ...

**Comment by liskamic** [comment]
I downloaded the newest version and the problem persisted (albeit with different error code) until I deleted all aux files from WTF folder.
Now works like a charm.
Many thanks for instant fix and keeping the awesome work!
