### ISSUE TITLE
Bug when trying to post items

### ISSUE THREAD

**Issue by DavidMoschner** [shirsig/aux-addon#146]
https://puu.sh/yzH8D/0175f32ae7.jpg

I just clicked on the Light Leather to try and post it, and it fails to do the search. I have been using this addon for a bit and it seems to be only happening for this item on this character. If you need any more information or have a workaround let me know.

**Comment by DavidMoschner** [comment]
Clicking refresh on the Post screen seemed to be a nice workaround, but I always got the error upon clicking the Light Leather for the first time.

**Comment by shirsig** [comment]
update if you don't have the newest version and enter a number into buyout (can be 0)

**Comment by DavidMoschner** [comment]
Yeah, I grabbed the latest version from master before posting. So it seems like there are a few workarounds, and I'm guessing it's not a common issue. Feel free to close.

**Comment by shirsig** [comment]
It seems like you had a corrupted buyout price for that item which was caused by another bug which hopefully shouldnt exist in the newest versi9n.
