### ISSUE TITLE
Aux naming convention

### ISSUE THREAD

**Issue by KevinTyrrell** [shirsig/aux-addon#148]
On Windows, you are unable to name a folder 'aux'. I feel like this was an oversight that should consider being changed. It's weird because in the interface folder it has to be named something different, like aux-addon or aux-master (the repo), etc. If you try to name it "aux" you will get an invalid driver error.

[See here](http://www.thewindowsclub.com/create-restricted-files-folders-con-aux-nul-click-windows)

**Comment by shirsig** [comment]
But ... you can't name it aux anyway (or aux-master for that matter). The folder name has to be the same as the .toc file name or the addon won't work.

**Comment by KevinTyrrell** [comment]
I suppose so, I just think maybe it's strange that the addon needs to be named "aux-addon" instead of aux, but it actually can't be named "aux" because you cannot create a folder of that name.
