### ISSUE TITLE
More selloptions

### ISSUE THREAD

**Issue by ziggestark** [shirsig/Aux-Addon#15]
Hello, it would be nice if we had an option to change the way the sell-page choose the sellprice. It would be nice to have a column that showed price per piece and not only the complete stack. And an option of undercut the lowest price per piece and not only a matching stack size. Cheers

**Comment by shirsig** [comment]
Hey, the first column does show the price per piece (called unit price there). If you want the suggestion based on the lowest unit price just select the first entry in the list (they're sorted by unit price).
