### ISSUE TITLE
Access Violation when posting auctions

### ISSUE THREAD

**Issue by KevinTyrrell** [shirsig/aux-addon#150]
The addon works for around 15 auctions but at some point posting auctions ends up giving me an access violation in memory. I'm playing on RetroWoW which is a vanilla server. I'm using the latest version. 

Doing aux/clear fixes the problem for a bit but it will come back. Of course doing clear doesn't help much because I lose the history. 

Any idea what could be causing this? I'm running WoW on an external hard drive. Also the vanilla server is not a 1.12.1 patch but a slightly different one. Still though, I wasn't aware an addon can lead to wow errors.

![ltq8nh4](https://user-images.githubusercontent.com/12791400/33963901-83fb272a-e00b-11e7-98a6-215931d981a3.png)

**Comment by shirsig** [comment]
aux/clear ?

**Comment by shirsig** [comment]
Are u sure its from the addon? I think you would get the same error when using the default interface. Used to be a common thing on nost too to get crashes for having too many auctions up.

**Comment by KevinTyrrell** [comment]
@shirsig That could be it, but after this error I switched to other auctioneer addons and didn't have any issues. It's been a long time since I reported this but one thing I maybe forgot to check is how much memory I gave my addons. I swear I put it to 999 MB, but even if I left it at default I don't think the game would hard crash like this.
