### ISSUE TITLE
duplicated saved searches

### ISSUE THREAD

**Issue by Meridaw** [shirsig/aux-addon#151]
Can you make Aux filter away duplicated saved searches?

**Comment by shirsig** [comment]
Sort of. I could make sure the same exact string is only shown once but it's not possible to detect in general if two queries have the same meaning (which can be the case even if the actual string is different) so I chose not to do it for the former either for consistency.

**Comment by shirsig** [comment]
Decided to do this after all (with the limitation I mentioned in my previous post, only works for syntactically identical searches)
