### ISSUE TITLE
string expected, got nil

### ISSUE THREAD

**Issue by Meridaw** [shirsig/aux-addon#157]
![aux1](https://user-images.githubusercontent.com/26133646/34467778-355079aa-eefb-11e7-817c-16e4ffa29225.png)

Get this some times, when i open some crafting skills in AdvancedTradeSkillWindow.

**Comment by shirsig** [comment]
This is with the recent version? The crafting addition checks for null there so it would have to be the tooltip extension ... maybe if AdvancedTradeSkillWindow does some sort of tooltip parsing using the gametooltip.

**Comment by Meridaw** [comment]
Yes, this is the most recent version of Aux and AdvancedTradeSkill from https://github.com/laytya/AdvancedTradeSkillWindow-vanilla . I only get it some times, mostly when i open Tailoring or First Aid. I also got https://github.com/laytya/LilSparkysWorkshop-vanilla that adds adds auction-derived pricing information for trade skills right into the trade skill recipe frame.
