### ISSUE TITLE
Twilight Cultist items not disenchantable

### ISSUE THREAD

**Issue by Sorafo** [shirsig/aux-addon#158]
twilight cultist items show in disenchant profit searches. they are not disenchantable, tooltip shows disenchant distribution also.  if there isnt a easily added lib of disenchantables maybe a option to blacklist certain items or remove disenchant properties?

**Comment by shirsig** [comment]
The disenchant distribution is based on the level required to use it. The game's api gives you no information about which items can actually be disenchanted, so the only way do exclude the ones that can't would be to manually compile a list of all of them. Not sure if I'll do that at some point, but in any case, there's already an issue for it: https://github.com/shirsig/aux-addon/issues/116
