### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vitoshka** [shirsig/aux-addon#159]
[2018/02/03 19:25:38-1990]: core\tooltip.lua:26: Invalid quest item in SetQuestLogItem("type", index)
<in C code>: in function `?'
core\tooltip.lua:26: in function <Interface\AddOns\aux-addon\core\tooltip.lua:23>
<unknown>:
<string>:"EQL3_QuestLogItem1:OnEnter":4: in main chunk

  ---

**Comment by Vitoshka** [comment]
**A new error occurred when I pick up mail**

[2018/03/08 11:40:46-2429]: core\tooltip.lua:152: Usage: GetItemQualityColor(index)
<in C code>: in function `GetItemQualityColor'
core\tooltip.lua:152: in function <Interface\AddOns\aux-addon\core\tooltip.lua:147>
core\tooltip.lua:26: in function <Interface\AddOns\aux-addon\core\tooltip.lua:21>
<unknown>:
FrameXML\MailFrame.lua:218: in function `InboxFrameItem_OnEnter'
Mail\Mail.lua:169: in function `InboxFrameItem_OnEnter'
<string>:"MailItem2Button:OnEnter":2: in main chunk

  ---

**Comment by shirsig** [comment]
Could you try to find out if it's a conflict with some other addon and which?
