### ISSUE TITLE
Possibility to sort items

### ISSUE THREAD

**Issue by furier** [shirsig/Aux-Addon#16]
Possibility to sort items by given column, price or item count etc...

**Comment by shirsig** [comment]
In the buy tab this has already been available for a while. Just click on the column headers to sort:
http://forum.nostalrius.org/viewtopic.php?f=63&t=21102&p=166661#p166661

If you're talking about the sell tab, I'm gonna add it there too eventually but I don't think it's as useful there anyway.

**Comment by furier** [comment]
Oh, then I must have an outdated version. Because I'm not able to sort
items. 😕 I'll have a look when I get home from work. ☺️
tor. 15. okt. 2015 kl. 01.24 skrev shirsig <notifications@github.com>:

**Comment by furier** [comment]
Updated to lates version, works like a charm! :)
