### ISSUE TITLE
Feature request: Default duration

### ISSUE THREAD

**Issue by Cephel** [shirsig/aux-addon#160]
I'd request the ability to set a default action duration (2, 8, 24) for all unknown or new auctions. It's a lot of extra clicks to just set everything new to 24 if you like to do that.

**Comment by FrostShock** [comment]
Most of the players set their auctions to 24 hours so yes, please implement this feature.

**Comment by shirsig** [comment]
You can now change the default with **/aux post duration 24** (warning: when upgrading to the newest version you lose your history)
