### ISSUE TITLE
Can we scan whole AH into a cache then do different search based on it?

### ISSUE THREAD

**Issue by twilightgod** [shirsig/aux-addon#164]
For example, I'm running two searches:
1. price is lower than vendor price at least 20s
2. price is lower than historical price at least 50%

I don't want to mix up the results into one search, since in the first type, I will bid/buy it out, but for the second one, if it's an item with short history, the price would be bias, I need to manually review it.

Right now I need to scan AH twice for long time, I'm thinking about can we make a cache for that? Or a way to separate these two search results in different list.

Thanks

**Comment by shirsig** [comment]
If you're automatically buying out for the first one you can just make an auto buyout query in the saved searches listing like this: vendor-profit/20s
Then do a full scan with percent/50. The auto buy query will buyout everything with 20s vendor profit in the background and only the results of the second query will be listed in the table.
