### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by elzeardbouffier** [shirsig/aux-addon#166]
I've been getting this error when trying to search anything:

> aux-addon\gui\auction_listing.lua:533: attempt to perform arithmetic on a nil value

A few times search works perfectly fine, but I wasn't doing anything different (as far as I know).

**Comment by shirsig** [comment]
there has been no significant change in a long time and no one else has reported this so it's most likely just a savedvariables issue.

**Comment by elzeardbouffier** [comment]
Deleting my WTF folder seemed to fix it. Ideally I'd be able to surgically remove some savedvariable file, but I've had no luck with either SavedVariables/aux-addon.lua or ACCOUNT/SavedVariables.lua. (Admittedly I don't really know what I should be deleting.) Thanks for your response and the great addons nonetheless!

**Comment by shirsig** [comment]
Aux doesnt use that anyway, youd have to delete the main aux file for your account.

**Comment by elzeardbouffier** [comment]
Deleting the main aux file does not work.

**Comment by shirsig** [comment]
Did you delete it while the client was running? You have to shut down the client then delete then restart.

**Comment by elzeardbouffier** [comment]
I deleted it while the client was shut down and the problem remains.

**Comment by shirsig** [comment]
Anything unusual about your client?
Are you playing on server other than the 3 most popular ones?

Are you certain you have the newest version of aux? (To be safe you should delete the folder and download the zip, git pull may have issues with case in file names.

Are you certain you deleted the right account's savedvariables?

**Comment by elzeardbouffier** [comment]
1) I'm using the MacOS client. Would that make a difference?

2) Just Northdale.

3) Yes, newest version.

4) Yes, correct account.

I also regularly get this split-column view. I don't know if it's connected. https://imgur.com/a/kI0txvg

**Comment by shirsig** [comment]
The two post listings are a feature toggled by **/aux post bid** and a reload.

No idea about the mac, I've never used one.

Did you ever try disabling all other addons?
Also, to be absolutely sure it's an aux bug (which I'm very skeptical of because it happens on every search and no one else has reported it) could you try downloading a fresh client, installing only aux and then teying again?

**Comment by elzeardbouffier** [comment]
Sorry, I should've isolated this from the beginning. It looks like it pops up when pfui is enabled. I'll see if anyone in shagu's Discord has an idea.

**Comment by albei** [comment]
I can post items but cannot search/scan.
Errors I get with latest version of aux, pfui on a mac. If i disable pfui it works.
Have the same setup on windows and i don't get any errors. 
On mac:
[2019/03/13 11:44:56-24-x1]: gui\auction_listing.lua:533: attempt to perform arithmetic on a nil value
gui\auction_listing.lua:533: in function `ResizeColumns'
gui\auction_listing.lua:688: in function `UpdateRows'
gui\auction_listing.lua:867: in function <Interface\AddOns\aux-addon\gui\auction_listing.lua:854>
<unknown>:
search\results.lua:86: in function `new_search'
search\results.lua:13: in function `f'
aux-addon\aux-addon.lua:46: in function <Interface\AddOns\aux-addon\aux-addon.lua:40>

  ---
[2019/03/13 12:50:44-24-x1]: gui\auction_listing.lua:533: attempt to perform arithmetic on a nil value
gui\auction_listing.lua:533: in function `ResizeColumns'
gui\auction_listing.lua:688: in function `UpdateRows'
gui\auction_listing.lua:822: in function `SetDatabase'
search\results.lua:247: in function <Interface\AddOns\aux-addon\tabs\search\results.lua:246>
core\scan.lua:132: in function <Interface\AddOns\aux-addon\core\scan.lua:128>
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
<unknown>:
aux-addon\control.lua:46: in function <Interface\AddOns\aux-addon\control.lua:28>
