### ISSUE TITLE
Populate WDB error

### ISSUE THREAD

**Issue by Bedevir** [shirsig/aux-addon#167]
Hello,

This is what I encountered when I tried to populate the WDB.

Error:  attempt to call field `populate_wdb' (a nil value)
AddOn: aux-addon
File: slash.lua
Line: 54
Count: 1

Also populating the WDB means to get the data from informant to aux?

Thank you for the answers!

**Comment by shirsig** [comment]
Not sure why it's not working anymore but you don't need to use it anyway, it was meant mainly for testing. What it does (should do) is trying to request all item info from the server and load it into your wdb cache.
It has nothing to do with item prices. If you want a price database you need this: https://github.com/shirsig/aux_merchant_prices

**Comment by shirsig** [comment]
fixed it. but as I said, not much of a point in using it anyway. also some servers might still disconnect you while it's running because it's creating "a lot" of traffic.
