### ISSUE TITLE
Scan auction house

### ISSUE THREAD

**Issue by furier** [shirsig/Aux-Addon#17]
Let users scan auction house to build up a database of prices on items with timestamps. With such a database you could display trends for prices on items and check on what time of the day items are cheapest or most expensive, what week day etc..

Also would be nice to see average prices for items in the tool tip like with auctioneer.

**Comment by shirsig** [comment]
This will be the next step after I'm done with the new UI. Check out this thread for more info about coming features: https://forum.nostalrius.org/viewtopic.php?f=63&t=21102&start=100
Haven't really been keeping the issues on github up to date.
