### ISSUE TITLE
Merchant price

### ISSUE THREAD

**Issue by Bedevir** [shirsig/aux-addon#172]
Hello again,

I'd be curious if there is a way to macro a search for those items which are lower than merchant (NPC) price? I find some items which are lower than the MP even if it means only coppers. Still I can't find out what to write into the search bar.
Thank you for the answer!

**Comment by shirsig** [comment]
I think it's vendor-profit/1c (for at least 1c profit) though it will only work for items youve already had when visiting a vendor, unless you import vendor prices with the aux_merchant_prices addon and I cannot guarantee the correctness of those (prices might vary by server or patch or just be plain wrong) though still chances are high theyre correct but u should always buy one and verify before u mass buy something
