### ISSUE TITLE
Real time scan

### ISSUE THREAD

**Issue by Cavader** [shirsig/aux-addon#173]
Playing on Kronos 3 atm and can't get the real time scan to work :(

**Comment by shirsig** [comment]
Yeah, the AH sorting is not blizzlike so it's not possible. The newest auctions aren't added to the last page but I guess to a random one.

What you can still do is make a blizzard query that returns less than one page of results, then you can snipe for items part of that query.

A bigger problem for me is that the server constantly disconnects me, like every 3 minutes or so. Do you get that to? Not even just when I'm idling. It was fine for a few days two weeks ago then it started again.

**Comment by Cavader** [comment]
Oh what a pity.
Query = 1 page on the AH? And how would I go about doing that? That sounds like I might be able to snipe some stuff.

No that's weird, I don't get DCs like that (playing in Europe, using the west / east login servers).

Thank you for taking time to reply, I really appreciate it.

**Comment by shirsig** [comment]
Well, if you only want to snipe for one specific item you could make a search only for that item. If you want to snipe for multiple items that are in a similar category it might also work to have a query for that category (e.g., something like armor/plate/49/49 if you want to snipe for some 49 twink items or whatever) but sniping for unrelated items in general won't work as you can't get them all into a search that will return only one page.
