### ISSUE TITLE
Populate WDB function not working

### ISSUE THREAD

**Issue by Sabre142** [shirsig/aux-addon#175]
I can't seem to enter the command /aux populate wdb .

**Comment by shirsig** [comment]
Getting an error? Then u need to update your aux version. In any case, you dont really need to use this and it might also disconnect you because of the traffic it generates.

**Comment by Sabre142** [comment]
Downloaded latest revision just now. Disabled all addons except aux.

![capture](https://user-images.githubusercontent.com/26516348/42389176-3418db0e-818b-11e8-8799-043bd88836c8.PNG)

**Comment by shirsig** [comment]
Very strange. Make sure you update properly, delete the folder and diwnload the fresh zip or clone again. Sometimes there can be problems with file name capitalization on windows for example when pulling.

**Comment by Sabre142** [comment]
Did delete and downloaded completely fresh but yeah, does it work on your end

**Comment by shirsig** [comment]
Yeah it works since the fix which wasn't too long ago. Someone else reported it a while ago. Are you getting any other errors like on startup? Maybe deleting the savedvariables could help.

**Comment by Sabre142** [comment]
Nah no other errors. Deleting savedvariables didn't help.

**Comment by shirsig** [comment]
Lol, looks like I forgot to push the fix, that's why it was working for me. Now it should work, sorry.
