### ISSUE TITLE
Allow hiding of crafting reagents total

### ISSUE THREAD

**Issue by codestothestars** [shirsig/aux-addon#178]
Are you open to allowing the `Reagents: (Total Cost: X)` text in the profession window to be hideable? I use this addon purely for the auction house UI and find this text distracting.

If you are open to this change but don't have the time, I'd be happy to open a pull request. Please let me know! Thank you for this great addon.

**Comment by shirsig** [comment]
Added the setting as **/aux crafting cost**
It currently requires a /run ReloadUI() to take effect like some other settings. Will at some point improve them all to apply immediately.
