### ISSUE TITLE
duplicate information

### ISSUE THREAD

**Issue by Lichery** [shirsig/aux-addon#180]
If enabled "aux post bid":
![bandicam 2018-09-09 13-29-18-019](https://user-images.githubusercontent.com/24303693/45263604-b30be380-b434-11e8-8fa8-67ee0fc27683.jpg)

I suggest deleting columns "Auctions", "Time Left", "Stack Size" and doing something like this:
![bandicam 2018-09-09 13-34-24-835](https://user-images.githubusercontent.com/24303693/45263640-c4092480-b435-11e8-9ea3-e54a830c5dad.jpg)

**Comment by Lichery** [comment]
By the way, I also propose to improve the option "aux post bid". In order for the changes to take effect, need reloadUI, but you have not written it anywhere. Maybe should write to the chat command about this or do a StaticPopupDialogs ?

**Comment by shirsig** [comment]
The tables are not showing individual auctions and are not grouped by the same criteria so they cannot be combined

**Comment by shirsig** [comment]
As for the reloading notification i dont think ill bother. If i ever get around to it ill just fix it instead, shouldnt be that much more work.
