### ISSUE TITLE
An option for setting Unit Starting Price = Unit Buyout Price

### ISSUE THREAD

**Issue by FrostShock** [shirsig/aux-addon#184]
Hello again,

When I post an auction, I always set the Unit Starting Price to the same Unit Buyout Price, can you please add a checkbox for that?
If checked, then, when you complete one of these two fields, the other field should be automatically filled with the same value.
That would help the users like me to save a lot of time, by not filling so many times the same values twice.

Thank you

**Comment by Altoholic** [comment]
I think it's the default now ? No checkbox, but the prices always are the same in both fields.
Maybe that bug report can be closed.

**Comment by shirsig** [comment]
It is the default for automatic undercutting, though if you manually enter a price it won't automatically match the two prices, but I don't think this is a common enough case to warrant making the UI more complicated.
