### ISSUE TITLE
Feature request: buy multiple items with a single click

### ISSUE THREAD

**Issue by FrostShock** [shirsig/aux-addon#185]
Hello, I would like to ask for implementing this feature:
In the search window, allow the users to select multiple items and then to buy them all with a single click on a "Buy All" button.

In WotLK, I am using the Auctionator addon (ver 2.6.3) to buy multiple items at once from the Auction House (AH). I am using the "Buy" tab.
Would be very nice to have such a feature in Vanilla WoW too.

Thank you!

**Comment by shirsig** [comment]
That seems to add unnecessary complexity to me. There already is the alt-click shortcut to buy, so why not buy them directly rather than selecting and then clicking buy all.

**Comment by shirsig** [comment]
Also not possible anyway in classic.
