### ISSUE TITLE
Feature request: Search items by seller

### ISSUE THREAD

**Issue by FrostShock** [shirsig/aux-addon#189]
Hello,

I would like to place this feature request: help the users to transfer items through the neutral auction house by allowing them to search the name of the seller, like this addon for example [AuctionHelper](https://github.com/EinBaum/AuctionHelper)

Thank you

**Comment by shirsig** [comment]
There is now a seller filter (**seller/_name_**)
However, note that the setting **/aux ignore owner** is turned on by default which means if you make a fresh scan of a page owners are almost never retrieved and those auctions would thus be ignored with a seller filter. For whatever reason the seller names are retrieved by the wow client later than all other auction data which is retrieved immediately. However, once an owner name is cached I think it will always be there immediately so this would work for repeated scan of the same page of the neutral AH. For it to always reliably work however you would have to disable that setting which will significantly slow down scanning.
