### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by cryohellinc** [shirsig/Aux-Addon#19]
Latest version of addon, when typing anything in search box, not results are ever displayed. 

Cleaned WDB folder, cleaned cache folder, cleaned Aux files in "saved variables". When posting items, it works normally.

**Comment by shirsig** [comment]
Strange, mine is working fine. Do you have a client with a different locale than english? Still even if you do there was no change in that area in any recent update.

**Comment by cryohellinc** [comment]
Client is English, nothing was changed with locale. Previous Aux versions ( before latest UI change ) were working. Also recent one, when you turn it on, drops the fps by 80% for some reason.

**Comment by shirsig** [comment]
Oh, so you updated from a very old version. Maybe you're misusing the search, there have been a lot of changes. What are you typing into the searchbox? What happens when you search with an empty searchbox?
As for the performance, what do you mean by turning on? Opening the ah or starting a search? There was a change in the search that is kind of suboptimally implemented right now (waiting for complete owner data) but it lowers my fps by maybe 10% at most.

**Comment by shirsig** [comment]
Also note that loading a page (with complete owner data) can sometimes take reeaaally long if you're playing on the pvp server (like, 20+ seconds). The lag there is getting insane.

**Comment by shirsig** [comment]
I've made some changes to the scanning now which should solve your fps issue (if it was because of scanning). Unfortunately because the API is so terrible there's really no fully satisfactory way to do scanning. There's no way of knowing for sure if a response from the server is really the response to your last query. I'm using a delay based method now instead of the owner check from before which should be better for performance but has other drawbacks.

**Comment by xak1989** [comment]
+1 search does not work, I updated here 2 weeks ago, worked well, finding a new update today, I installed and it stopped working. Right now I updated again and again does not work.

**Comment by shirsig** [comment]
What do you type into the searchbox? What's happening exactly? What does the progress bar say? My search is working fine both on pvp and pve.

**Comment by cryohellinc** [comment]
Thank you shirsig for your effort, i will do some testing tomorrow. Lets get to the bottom of this. Will post once done with your suggestions / tests. 

And no, not a very old version, the previous UI version.

**Comment by shirsig** [comment]
Actually, that's what I meant by old :)

**Comment by cryohellinc** [comment]
Latest version you updated 4 hours ago, works perfectly. Thank you!

**Comment by cryohellinc** [comment]
updated from version which was released 7 days ago, deposit / post button grayed out, rolled back to previous version. what can be the issue?

**Comment by shirsig** [comment]
Did you use "/aux clear post"? Not sure if that could be causing it but in any case, always follow the nost forum thread for possible update instructions. What do you mean by deposit?

**Comment by shirsig** [comment]
Note there are many valid reasons why the post button could be grayed out. The bid price could be 0, the buyout could be larger than the bid, you could have selected a larger stack size than what you have in your inventory and not "post all" and maybe some more.

**Comment by xak1989** [comment]
still not work (last version) 
![wowscrnshot_030916_200519](https://cloud.githubusercontent.com/assets/16578229/13643699/1fce0f52-e633-11e5-9293-d7ef7853ba9b.jpg)
When i return to 1 month ago version, all work fine... no idea what is goin on but is unpleasant that I can not use the latest version. I have about 200 addons (yea, and its work very comfortably) so not an option to check with what it was in conflict

**Comment by shirsig** [comment]
Well, some more information besides "doesn't work" would be helpful. Does only the search tab not work? does it work for some other queries? What happens exactly? Which server are you playing on? etc. etc. You could at least disable every other addon to see if it is a conflict, even if you can't find out exactly with which one. Also I assume you've tried the usual fixes for update breakages from the nost thread? /aux clear /aux delete item cache

**Comment by xak1989** [comment]
omg, i am retarded. Deleting Aux files from SavedVariables folders fix my problem, so you can recommend it to resolve problems, thx

**Comment by cryohellinc** [comment]
After rolling back and waiting for couple of weeks, decided to update to latest version. Same issue, bid's dont work.

Cleaned Aux folder / cleaned variables folder  Aux files - both the default one and one for the character.

Search works, buyout works, post seems to be still messed up.

![ah 1](https://cloud.githubusercontent.com/assets/17429806/13775416/08451906-eaad-11e5-90b8-1452d316c0b3.PNG)

as an example lets take Winter squid, click on it on left column, this is what i see. Before it would scan the market for prices and give me best possible undercut / bid price. Now both of the fields are blank, if i manually put in the data i can post, otherwise post button is grayed out. 

If i click on any other auctions for squid in the bottom, it does this 
![ah 2](https://cloud.githubusercontent.com/assets/17429806/13775469/632877b4-eaad-11e5-8d6f-41f5bf4d7477.PNG)

Sets the bid price and undercuts it, but still not buyout value. 

Am i doing something wrong? I did even the /aux history clear ( if im spelling it right, copied the command from forums ) 

Or is it simply a bug?

**Comment by shirsig** [comment]
You have to click on the buy column to undercut buyout prices and on the bid column to undercut bid prices. I've written quite a lot on this change in the nost forum thread. Also the color coding and what you would want to pay attention to when undercutting.

**Comment by cryohellinc** [comment]
shirsig

Thank you, will read it. :)

**Comment by shirsig** [comment]
This post explains the color coding:
http://forum.nostalrius.org/viewtopic.php?f=63&t=21102&p=257331#p257331

As you've noticed the automatic undercutting is gone. There are two reasons for that. One was that the fixed price and undercutting modes were merged for the sake of simplicity and now the price is always remembered. Automatically changing it after the scan is finished would be a bit strange. The second reason is that it really did not give you the "best possible undercut / bid price". What it did is undercut the lowest buyout, not even considering the bids of other auctions. As I explain in the post linked above this is most of the time really not what you want/will make you lose gold. The considerations you have to make for the right undercut can't really be automated well.
