### ISSUE TITLE
Vendor Sell Value not working

### ISSUE THREAD

**Issue by mrrosh** [shirsig/aux-addon#191]
After the latest update, the tooltip merchant sell value isn't working anymore. Any way to fix this?

**Comment by shirsig** [comment]
Are u sure the tooltip is broken and not just the database empty? (If u were using the aux merchant price database addon u have to update that too)

**Comment by mrrosh** [comment]
Most likely the database is empty. I do use aux merchant price but there's no update to it. Latest one is from 8 months ago.

**Comment by shirsig** [comment]
Oh, guess i forgot to push it, will do it later today, thanks.

**Comment by mrrosh** [comment]
Works fine now, thank you!
