### ISSUE TITLE
Outbidded bids disappearing?

### ISSUE THREAD

**Issue by yarvaxea** [shirsig/aux-addon#193]
Whenever someone outbids me on auctions they just disappear instead of saying Outbidded so I can bid again. Sometimes it appears as Outbidded but once I click on the auction it disappears. This seems to only be the case when I've bidded on many auctions. If someone buyouts the auction this should be the case, but many times I can find the exact same auction and I can then bid again.

The Bids list doesn't show all items either, but sometimes it does.
Look:
![silver ore](https://user-images.githubusercontent.com/26580922/59727187-f3ef1f00-9234-11e9-9260-4b15f0e85bfe.PNG)
The Blizzard UI says I have a bid on Silver Ore, but it doesn't appear in the Aux frame.

**Comment by shirsig** [comment]
Is it the same with the default AH? If yes it's a server problem and
nothisng I can do.

**Comment by shirsig** [comment]
I cannot reproduce this (on Kronos). Interestingly the bids also disappear from the default ah. I logged out and logged back in when I had been outbid though. Perhaps the default AH keeps them and updates them when you're there while it happens? Still seems kind of strange though because it does essentially the same scan as aux.

**Comment by yarvaxea** [comment]
Ah shit I forgot to reply. I tried using only the Blizzard interface, no addons active at all. When only a few auctions are bidded on it works as intended, but if you have lots of bids it bugs out and disappears after you outbid one of them. I asked in support on the Lightshope discord and they guessed it was something with the server itself that was bugged. So I guess it's a server-side bug then and it just won't work on Lightshope.

The other thing which is that Aux doesn't list all your bids I don't know if is server side. Sometimes it shows all bids if I press Refresh, I can't reproduce it though so I have no clue what's going on there.

**Comment by shirsig** [comment]
It may well be that there's some subtle bug. The vanilla interface for auctions and bids is actually super weird. They're both paginated but both in a different different way from the search.

Retail vanilla is using the TBC and later interface so far where they're not paginated and just a single call is necessary to load them all and then there's an event for updates.

**Comment by yarvaxea** [comment]
Will you make a Classic version of Aux? It's by far my favourite vanilla addon so I would love to continue using it on Classic.

**Comment by shirsig** [comment]
Yes. Here is some information about it: https://www.reddit.com/r/classicwow/comments/bxf1lc/aux_auction_house_addon_experimental_classic/

**Comment by shirsig** [comment]
https://www.curseforge.com/wow/addons/aux
