### ISSUE TITLE
Question about the colors for Historical Value

### ISSUE THREAD

**Issue by ChristopherNorthcube** [shirsig/aux-addon#194]
Just a quick question, can't find any information for it. I regularly see blue color, green color, red color, and gray color. What do they mean? I take it that red is overpriced, green is underpriced, but what is blue and gray?

**Comment by shirsig** [comment]
Blue, green, yellow, orange, and red have no independent meaning. The percentage just takes those colors depending on how high it is.

Gray means that there is no buyout price for this auction and the percentage (regardless of how high) is based on the bid.

**Comment by ChristopherNorthcube** [comment]
Thanks for a quick response. Love your addon by the way.
