### ISSUE TITLE
Lua Error on Classic Stress Test

### ISSUE THREAD

**Issue by tommysp86** [shirsig/aux-addon#195]
Message: Interface\AddOns\aux-addon\core\tooltip.lua:24: Invalid quest item in SetQuestItem("type", index)
Time: Thu Aug  8 23:50:53 2019
Count: 1
Stack: Interface\AddOns\aux-addon\core\tooltip.lua:24: Invalid quest item in SetQuestItem("type", index)
[C]: in function `?'
Interface\AddOns\aux-addon\core\tooltip.lua:24: in function `SetQuestItem'
...terface\AddOns\Storyline\rewards\rewards_buttons.lua:41: in function <...terface\AddOns\Storyline\rewards\rewards_buttons.lua:39>

Locals: (*temporary) = GameTooltip {
 0 = <userdata>
 Shadow = <unnamed> {
 }
 SetHyperlink = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 SetTradeSkillItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 _owner = QuestieFrame66 {
 }
 questOrder = <table> {
 }
 SetCraftItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 IsSkinned = true
 TopOverlay = <unnamed> {
 }
 npcOrder = <table> {
 }
 SetLootItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 SetQuestItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 numMoneyFrames = 1
 SetInboxItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 SetQuestLogItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 BottomOverlay = <unnamed> {
 }
 hasMoney = 1
 SetCraftSpell = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 BorderIsCreated = true
 BorderTop = <unnamed> {
 }
 updateTooltip = 0.100000
 SetInventoryItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 BorderLeft = <unnamed> {
 }
 comparing = false
 SetAuctionSellItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 SetBagItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
 needsReset = true
 SetAction = <function> defined =[C]:-1
 BorderBottom = <unnamed> {
 }
 BorderRight = <unnamed> {
 }
 SetAuctionItem = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:21
}
(*temporary) = "choice"
(*temporary) = 3

**Comment by padmanek** [comment]
`Message: Interface\AddOns\aux-addon\aux-addon.lua:69: attempt to call field '?' (a nil value)
Time: Fri Aug  9 21:14:20 2019
Count: 2
Stack: Interface\AddOns\aux-addon\aux-addon.lua:69: attempt to call field '?' (a nil value)
Interface\AddOns\aux-addon\aux-addon.lua:69: in function <Interface\AddOns\aux-addon\aux-addon.lua:57>

Locals: _ = <unnamed> {
 0 = <userdata>
}
event = "AUCTION_OWNED_LIST_UPDATE"
arg1 = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call field '?' (a nil value)"
handlers = <table> {
 1 = <function> defined @Interface\AddOns\aux-addon\aux-addon.lua:74
 2 = <function> defined @Interface\AddOns\aux-addon\control.lua:12
 3 = <function> defined @Interface\AddOns\aux-addon\frame.lua:5
 4 = <function> defined @Interface\AddOns\aux-addon\core\cache.lua:13
 5 = <function> defined @Interface\AddOns\aux-addon\core\cache.lua:39
 6 = <function> defined @Interface\AddOns\aux-addon\core\tooltip.lua:15
 7 = <function> defined @Interface\AddOns\aux-addon\tabs\search\core.lua:18
 8 = <function> defined @Interface\AddOns\aux-addon\tabs\search\results.lua:12
 9 = <function> defined @Interface\AddOns\aux-addon\tabs\search\saved.lua:8
 10 = <function> defined @Interface\AddOns\aux-addon\tabs\post\frame.lua:314
 11 = <function> defined @Interface\AddOns\aux-addon\core\crafting.lua:10
}
event_frame = <unnamed> {
 0 = <userdata>
}
handlers2 = <table> {
 1 = <function> defined @Interface\AddOns\aux-addon\aux-addon.lua:213
 2 = <function> defined @Interface\AddOns\aux-addon\core\history.lua:12
 3 = <function> defined @Interface\AddOns\aux-addon\tabs\post\core.lua:33
}
`

**Comment by shirsig** [comment]
Thanks. I'll look into it in the afternoon. By the way, could you also tell me what _did_ work please?
Also, an unrelated question: is it true that the mailbox supports bulk operations without addons?

**Comment by tommysp86** [comment]
If you have a subscription active, you can play with the addon till monday, the stress test is still up!
The only quality of life feature they added to the mailbox is bulk mail, you don't have anymore to send 1 mail for every item, you can send multiple items on a single mail. For the rest, opening, reading, collecting items is still the same. So an addon to automate opening/reading/collecting money/items is still needed!

**Comment by shirsig** [comment]
Oh, I thought I needed a special invite. Thanks a lot for the info :)

**Comment by Jakobud** [comment]
What is the status of Aux support for Classic? Is it working?

**Comment by padmanek** [comment]
> What is the status of Aux support for Classic? Is it working?

IMO works perfectly. I love it :)
