### ISSUE TITLE
LUA Error on Classic Test

### ISSUE THREAD

**Issue by thecardinal5483** [shirsig/aux-addon#196]
Message: Interface\AddOns\aux-addon\libs\T.lua:19: attempt to call a table value
Time: Sun Aug 11 15:34:44 2019
Count: 546
Stack: Interface\AddOns\aux-addon\libs\T.lua:19: attempt to call a table value
Interface\AddOns\aux-addon\libs\T.lua:19: in function <Interface\AddOns\aux-addon\libs\T.lua:18>

Locals: (for generator) = <table> {
  = true
  = true
  = true
  = true
  = true
}
(for state) = nil
(for control) = nil
(*temporary) = <table> {
  = true
  = true
  = true
  = true
  = true
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call a table value"
auto_release = <table> {
  = true
  = true
  = true
  = true
  = true
}
release = <function> defined @Interface\AddOns\aux-addon\libs\T.lua:39
wipe = <function> defined @Interface\AddOns\aux-addon\libs\T.lua:8

The above error repeats until addon disabled

**Comment by vazheel** [comment]
Also getting this - it just increments the counter of errors until the WoW UI slows down or you disable aux

**Comment by shirsig** [comment]
Looks like you used the master branch. The "retail" branch is for retail classic. Master is for 1.12.
