### ISSUE TITLE
[Request] Quick scan

### ISSUE THREAD

**Issue by goudekid** [shirsig/aux-addon#201]
Classic wow implements the quick scan API (not sure what it is, but it's working in Auctionator) so it'd be nice if there was a button to get results using that rather than a full normal scan.

**Comment by mooreatv** [comment]
+100 and I'd like we integrate with my https://github.com/mooreatv/AuctionDB ideally to reuse that quick scan I have there

**Comment by MarkusKluge** [comment]
Quick scan allows auctioneer to scan everything within like less than 2 seconds. I hope this gets added because I still think aux has the best UI for searching/posting auctions. Thanks!

**Comment by shirsig** [comment]
Yes, I'm planning to add it.

**Comment by shirsig** [comment]
I've added a first basic version of the getAll scan now. You can use it with **/aux scan** (no gui interface yet). So far it's only used for the history but I will later integrate it with the post tab too. It currently takes about 1 minute to scan 1000 pages with minimal lag. I will keep tweaking the parameters to improve scan time and performance.

**Comment by dagochen** [comment]
When i use a filter, it still starts scanning for like 15 minutes...

**Comment by shirsig** [comment]
I don't understand.

**Comment by dagochen** [comment]
or/and2/profit/5g/percent/60/and3/bid-profit/5g/bid-percent/60/left/30m

i used this one. and it scans all items again, although i just used /aux scan

**Comment by MarkusKluge** [comment]
Should there be a new commit for this or was it included in the one yesterday?

**Comment by MarkusKluge** [comment]
Okay now there is the new commit. @dagochen you should download the new version now. You probably didnt have the version with the quick scan yet.

**Comment by shirsig** [comment]
Sorry, forgot to push it here.

All that /aux scan does at the moment is scan the prices for the historical value.

The next step will be to integrate it with the post tab so there is no time wasted for scanning prices for undercutting.

Whether I will also make the scan results available for searching with filters is something I haven't decided yet. Maybe there will be a toggle to either search live or search in the last getall scan results. Currently the results table is not optimized for dealing with this large a data set though so it will require a larger change.

**Comment by ClockWise89** [comment]
Has this been removed again? When doing /aux scan I get a list of possible commands, i.e. scan isn't one.

**Comment by MarkusKluge** [comment]
If I am not wrong there is a "SCAN" button in the UI that does exactly that (newest version)

**Comment by shirsig** [comment]
Yeah, there's a button for it now so I removed the slash command.
