### ISSUE TITLE
[classic] auto buy lua error

### ISSUE THREAD

**Issue by mooreatv** [shirsig/aux-addon#202]
2x [ADDON_ACTION_BLOCKED] AddOn 'aux-addon' tried to call the protected function 'PlaceAuctionBid()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `PlaceAuctionBid'
aux-addon\aux-addon.lua:140: in function <aux-addon\aux-addon.lua:137>
(tail call): ?
(tail call): ?

(need that hw event I guess)

**Comment by shirsig** [comment]
Yeah it's not possible. Not sure if I'll remove it completely or replace it with an alert. Actually not sure if sniping is possible anyway with the non vanilla like page order.

**Comment by mooreatv** [comment]
can you queue items with some mousewheel binding or spacebar or such ?

though I guess it's minor, maybe best to work on full scan integration instead and then fast search can be done by the user and pick whichever they want to actually buy
