### ISSUE TITLE
removing filters

### ISSUE THREAD

**Issue by padmanek** [shirsig/aux-addon#205]
I've added a tooltip filter with "agility" in it. How do I remove it?

**Comment by shirsig** [comment]
I don't understand, added in the searchbox? then you can just type something else instead.

**Comment by c-stoeckl** [comment]
I cannot remove post filters in the filter builder as well. I think you're supposed to right click them? It does not work in wow classic with the retail branch.

**Comment by shirsig** [comment]
Oh, I see. May well be that the right clicking is broken, I'll have a look at it.
But anyway, the filter builder is only an assistant for writing queries. You can always export it to the search box and edit it manually and you don't have to use the filter builder at all and can just type in the search box directly.

**Comment by c-stoeckl** [comment]
Thanks for the fast reply. Yes, I'm doing that already. Would be nice if it was fixed though :)

**Comment by padmanek** [comment]
Sorry I was asleep. It was indeed the right click to remove from filter builder that is broken. :)

**Comment by shirsig** [comment]
Ok it's fixed now. Also the scrolling in the post filter builder was broken. Now you can scroll to zoom.
