### ISSUE TITLE
Bid prices not listed in Post screen

### ISSUE THREAD

**Issue by robmonte** [shirsig/aux-addon#208]
Seeing bid prices is important when posting an item particularly because the vanilla AH interface doesn't sort prices by buyout. We can't undercut bid prices using aux currently as it doesn't list the current listings' bid prices along with the buyout prices as it did for private servers.

**Comment by mooreatv** [comment]
Quick plug if I may in the meantime if you use Auction House DataBase (AHDB), the tooltip shows you the current min bid so you can use to undercut (beware of not ending up selling stuff below vendor though)

**Comment by shirsig** [comment]
It's just disabled by default. You can enable it with **/aux post bid** (and reload the ui)

**Comment by robmonte** [comment]
Sweet, you're right. Didn't expect a defaults change compared to the 1.12 version.
