### ISSUE TITLE
Tooltips are broken

### ISSUE THREAD

**Issue by anthmarc** [shirsig/aux-addon#209]
Can't access any options to do with tooltips, only have /aux scale, ignore owner, and post bid.

Holding shift does not show value of stack either on AH or vendor.

Latest update broke this for me, last version was working!

**Comment by mooreatv** [comment]
maybe your options got reset? it works for me

is it showing "on" when you type /aux ?

**Comment by anthmarc** [comment]
Prior to deleting my wtf folder, when I typed /aux, the only options I had were scale, ignore owner, and post bid.  Nothing else.

So I deleted WTF and reinstalled aux.

I now have all options back, however, holding shift while mousing over an item still does not show the vendor or auction value of the stack, instead of just the vendor and auction value of a single unit when not holding shift.

**Comment by shirsig** [comment]
Yeah that's not a bug. I removed it because it simplified the tooltip code a lot, but I'll try to add it back later, hopefully in a nicer way somehow.

**Comment by shirsig** [comment]
The newest version has the stack values with shift again.

**Comment by anthmarc** [comment]
Thanks man. And thanks for making this addon.
