### ISSUE TITLE
shift clicking chat links doesn't copy item name in the aux search (like blizz UI does)

### ISSUE THREAD

**Issue by mooreatv** [shirsig/aux-addon#214]
My stuff prints item links in the chat window, I can shift click if I have the blizz AH open and it fills the item name for search, not with the aux search open

**Comment by shirsig** [comment]
I think you can alt-click it? Cant check right now.

**Comment by mooreatv** [comment]
Thanks ! Alt click works !!

is it on purpose that it's different than blizz? maybe so one can choose to send it to either?

**Comment by shirsig** [comment]
Actually in vanilla it was right click for both this and container items. Unfortunately this is not possible in classic. For container items shift click is already used so i made it alt for both for consistency. Actually maybe i'll make it work for shift also when i have time to avoid confusion for people used to the blizzard ah.
