### ISSUE TITLE
Nothing in post tab

### ISSUE THREAD

**Issue by Guvernor** [shirsig/aux-addon#215]
![auxposttab](https://user-images.githubusercontent.com/28607117/64130482-1e448780-cdf5-11e9-855f-31ab457a6031.png)

As seen in screenshot, the post tab is empty.
This is on a laptop with a fresh install of the game and no other addons installed so there shouldn't be any conflicts. (just wanted to do AH things on work laptop)
Latest version of aux as of posting this.

Reloading UI doesn't help.

**Comment by Guvernor** [comment]
Having alt-tabbed to post this and rreturning to the game, the tab is now partially populated but only lists 16 items (The ones contained in the default backpack)

**Comment by shirsig** [comment]
I assume this has been fixed.
