### ISSUE TITLE
Addon crash when changing roles in guild.

### ISSUE THREAD

**Issue by shadowerwtas** [shirsig/aux-addon#218]
Today i established my guild successfully and once i tried to promote some members to a higher rank i received errors that i need to disable aux addon every time i pressed the up arrow of promotion.

**Comment by shirsig** [comment]
Someone else has reported that too. No idea what the connection could be but I'll try to fix it this weekend when I'm back home.

**Comment by shirsig** [comment]
Do you have any more information? Is there a lua error (**/console scriptErrors 1** if you haven't enabled them yet)? I can't find any connection to aux from looking at the code.

**Comment by mooreatv** [comment]
this should help:
https://github.com/AeroScripts/QuestieDev/issues/697
(from https://us.forums.blizzard.com/en/wow/t/guild-master-cant-edit-guild-permissions/277494/4 )

**Comment by shirsig** [comment]
Thanks a lot. Could you check if it's working with the newest version please? (github not curse)

**Comment by mooreatv** [comment]
still getting
```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'aux-addon' tried to call the protected function 'GuildDemote()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `GuildDemote'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

**Comment by shirsig** [comment]
What about now? And if it's still not working, could you please try commenting out everything in core/shortcut.lua and check if that fixes it?
