### ISSUE TITLE
Add Readme file?

### ISSUE THREAD

**Issue by KevinTyrrell** [shirsig/aux-addon#22]
Hello, 

Could you please add a formalized readme file, including descriptions, how to use, and most importantly a contact information section so we can ask questions about AUX? 

Thank you.

**Comment by shirsig** [comment]
Hey, for now the main post in the nost forum thread contains some instructions though it's a bit outdated: http://forum.nostalrius.org/viewtopic.php?f=63&t=21102&sid=ef52b3b6d4408b5aaa8405ba1ec2653a

I'll eventually add a markdown file here but that may have to wait till the end of the semester.

I've added my gmail to the profile for questions.
