### ISSUE TITLE
Please consider adding support for other languages

### ISSUE THREAD

**Issue by DiscipleVIII** [shirsig/aux-addon#220]
Hi, I play the Taiwanese version of Wow classic (traditional Chinese characters) and unfortunately the addon doesn't recognize these characters, it all shows up as question marks. Could this functionality be added? Thank you

**Comment by SwimmingTiger** [comment]
你可以自行修改插件中引用的字體。
用[VSCode](https://code.visualstudio.com/)打開插件目錄，搜索“.TTF”，然後把所有找到的`xxx.TTF`替換爲`bLEI00D.TTF`，這是一個含有繁體中文字符的字體文件。
此外，`ARHei.TTF`是含有簡體中文的字體文件。

示例：
```
scroll_child:SetFont('p', [[Fonts\ARIALN.TTF]], gui.font_size.large)
```
->
```
scroll_child:SetFont('p', [[Fonts\bLEI00D.TTF]], gui.font_size.large)
```

**Comment by SwimmingTiger** [comment]
The above text describes the process of replacing fonts in the source code. Directly quoted font names have poor localization performance (any character that is not included in the font you reference may not be displayed). It is recommended to use the font constant:
```
scroll_child:SetFont('p', STANDARD_TEXT_FONT, gui.font_size.large)
```

Available font constants:
```
			STANDARD_TEXT_FONT
			UNIT_NAME_FONT
			DAMAGE_TEXT_FONT
```
From: https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/Fonts.xml

**Comment by DiscipleVIII** [comment]
Thank you! 謝謝

**Comment by shirsig** [comment]
Sorry, I thought this had been fixed already. Somehow missed those two font definitions. Is it fixed with the newest version (without any changes needed).
