### ISSUE TITLE
trying to post I can't because one of my item cause lua error and prevents scrolling

### ISSUE THREAD

**Issue by mooreatv** [shirsig/aux-addon#221]
21x aux-addon\gui\item_listing.lua:36: attempt to index local 'color' (a nil value)
aux-addon\gui\item_listing.lua:36: in function `render'
aux-addon\gui\item_listing.lua:128: in function `populate'
aux-addon\tabs\post\core.lua:115: in function `update_inventory_listing'
aux-addon\tabs\post\core.lua:543: in function <aux-addon\tabs\post\core.lua:538>

Locals:
self = <table> {
 item_records = <table> {
 }
 content_frame = <unnamed> {
 }
 scroll_frame = aux.frame15 {
 }
 selected = <function> defined @aux-addon\tabs\post\frame.lua:70
 rows = <table> {
 }
}
offset = 0
rows = <table> {
 1 = <unnamed> {
 }
 2 = <unnamed> {
 }
 3 = <unnamed> {
 }
 4 = <unnamed> {
 }
 5 = <unnamed> {
 }
 6 = <unnamed> {
 }
 7 = <unnamed> {
 }
 8 = <unnamed> {
 }
 9 = <unnamed> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <unnamed> {
 }
 2 = <unnamed> {
 }
 3 = <unnamed> {
 }
 4 = <unnamed> {
 }
 5 = <unnamed> {
 }
 6 = <unnamed> {
 }
 7 = <unnamed> {
 }
 8 = <unnamed> {
 }
 9 = <unnamed> {
 }
}
(for control) = 6
i = 6
row = <unnamed> {
 0 = <userdata>
 highlight = <unnamed> {
 }
 item_record = <table> {
 }
 mouseover = false
 item = <unnamed> {
 }
}
item_record = <table> {
 link = "|cffffffff|Hitem:724::::::::21:::::::|h[]|h|r"
 item_id = 724
 availability = <table> {
 }
 name = "Goretusk Liver Pie"
 aux_quantity = 8
 quality = 15
 key = "724:0"
 texture = 133952
 suffix_id = 0
}
color = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <userdata>
(*temporary) = "]"
(*temporary) = 1
(*temporary) = "attempt to index local 'color' (a nil value)"
T = <table> {
}
ROW_HEIGHT = 39

**Comment by shirsig** [comment]
Maybe try **/aux clear item cache** or deleting the savedvariables entirely?

**Comment by shirsig** [comment]
In the newest version there's also **/aux clear post** (+ **/run ReloadUI()**)
