### ISSUE TITLE
Max number of independent queries capped at 12

### ISSUE THREAD

**Issue by Haipethdev** [shirsig/aux-addon#225]
Running Aux on classic, I plug in every engineering mat (stones/bars) in to a query and it only resolves the first 12 (out of ~16).  I assume this is incorrect?

**Comment by shirsig** [comment]
It happened to mee too with less. There must be some bug that makes it randomly stio  Ill look into it.

**Comment by shirsig** [comment]
I think this has been fixed a while ago.
