### ISSUE TITLE
attempt to index file "results_listing" (a nil value)

### ISSUE THREAD

**Issue by jonasd1** [shirsig/aux-addon#23]
I always have this error lately when opening the auction house menu:

"Interface/Addons/aux-addon/search_frame.lua:193: attempt to index file "results_listing" (a nil value)"

any idea how I can fix that? Have tried to reinstall, using different client etc etc but I have no clue what kind of error that is or where to start with solving it.

Thanks in advance for your help :)

**Comment by shirsig** [comment]
Hey, you probably need to delete your savedvariables. Make sure your game isn't running when you delete it.

**Comment by jonasd1** [comment]
Hmm, deleting didn't help. I also had to re-download the aux-addon and delete the old version, weird. But it's working again, thx a lot! :) However, I can't seem to find the option "post all", is that gone in the newer version?

**Comment by shirsig** [comment]
Yes, there were inconsistencies with it. It was not clear what the behavior should be for items with charges and there's an issue with undercutting because the unit price may depend on the stack size. Also it generally makes sense to make different undercuts for different stack sizes anyway.

**Comment by KevinTyrrell** [comment]
I possibly have the same issue? This has happened multiple times after a certain number of days. The scans will work day after day but during one scan, I hit some point where it encounters a nil value. In this specific case, the thread k() appears to be null in control.lua. See the video here: 

https://www.youtube.com/watch?v=nEsezz0wNHU

**Comment by shirsig** [comment]
Hm, I would need to see the first of the errors which should be a different one.
