### ISSUE TITLE
Can't Post Item (Part 2)

### ISSUE THREAD

**Issue by ognennyy** [shirsig/aux-addon#231]
I read through the recent "Can't Post Item" thread at https://github.com/shirsig/aux-addon/issues/228 and I don't think my issue is related.  I decided to spawn a new thread for this post.

I attempted to post an item via the Aux interface.  I didn't have enough money for the 1.2 silver deposit on a stack of 17xLight Leather and as expected received an error telling me so.  I then went to a vendor and sold an item, which brought me to over 2s and gave me enough to cover the deposit.

When I returned to the AH I was going to post 3x String Wolf Meat but the "Post" button was grayed out; I was not able to interact with it; nothing happened when I moused over the button; it was unclickable.  I verified that I did in fact have the item selected in the Selected Item window above.  So I opened the default blizz UI AH screen and posted the item.  Thinking it was some buggy behavior specifically with Stringy Wolf Meat I moved on to post the Light Leather again.

Unfortunately I got the same behavior as I had gotten with the Stringy Wolf Meat.  At this point I did a /console reloadui, and Aux's Post button became usable again.

Could it be that there may be a bug that grays out the post button after you get an error for insufficient money to post but does not reset properly, and just keeps the button grayed out?  I just created my first character so I do not have enough items or money to try to replicate the behavior.  But hopefully in a few hours I will be able to do so, and will update the thread.

By the way, thanks a million for updating this addon to work with Classic.  I appreciate your selfless work.

**Comment by shirsig** [comment]
Yeah this is a known issue. I will have to spend some time looking at the classic API to find a better way for aux to confirm that auctioning was successful.

**Comment by GuerraReturns** [comment]
TEMPORARY FIX FOR ALL PEOPLE HAVE THIS PROBLEM:
Without lost Saves

Close WOW. <- IMPORTANT

Go to your WOW Folder -> WTF -> Account -> *accountnumer* -> SavedVariables

Cancel the file "aux-addon.lua.bak"


Download Notepad ++ (is the best)
In Notepad ++ (on top) press "lenguages" -> L -> Lua

Find you're bugged ID. In my case, i can't post Wool Cloth

Write on google : "*itemyoucan'tpost* ID WOW" (in my case: Wool CLoth id wow)
Open the first link, is 99% wowhead (in my case: https://classic.wowhead.com/item=2592/wool-cloth)

You can see the id inside the Link (in my case: 2592)

Go to Notepad:

Go to the top of the script
You have something like this:

	["faction"] = {
		["Flamelash|Alliance"] = {
			["post"] = {

Now , you have a lot of string like this:

				["6331:0"] = "3#25075#65090#0"
Find you're ID

				["2592:0"] = "mypriceu.u"

Cancel the string

BEFORE:
				["6331:0"] = "3#25075#65090#0",
				["2592:0"] = "3#0.001#150#0", <- BUGGED
				["13043:0"] = "3#59000#80000#0",

AFTER:
				["6331:0"] = "3#25075#65090#0",
				["13043:0"] = "3#59000#80000#0",

Save changes. (File -> Save)

Close Notepad


Start WOW

Enjoy, now you can post
