### ISSUE TITLE
About Chinese characters

### ISSUE THREAD

**Issue by ccnuyan** [shirsig/aux-addon#236]
Nice addon,  but all Chinese characters are question marks.
硬肉干 => ???

**Comment by ccnuyan** [comment]
or maybe where should I set the font?

**Comment by shirsig** [comment]
Not sure if it's used everywhere but the main font os defined near the top of gui/core.lua.

**Comment by ccnuyan** [comment]
solved by manually set Fonts/*.ttf under ./_classical, thank you shirsig

**Comment by caijiang** [comment]
Fonts/*.ttf 在哪里？我这没有这个文件夹。

**Comment by shirsig** [comment]
Is the font issue fixed in the newest version? (without any changes from you)

**Comment by ccnuyan** [comment]
@caijiang After installation with default settings, there are no Fonts and Fonts/*.ttf under ./classical, you should try to set up the Fonts folder and Fonts/*.ttf manually.

**Comment by shirsig** [comment]
So it's not working? I'm using a predefined font family now, not explicit paths to font files anymore. Also I don't understand, I mean, there must be some fonts in the default install or how do you see any text at all? Addons cannot create any folders or files outside the addons' own directories.
