### ISSUE TITLE
streaming error when /aux scan

### ISSUE THREAD

**Issue by dinotheextinct** [shirsig/aux-addon#237]
When ever I use /aux scan I get a streaming error and a disconnect after few seconds. Wow Classic.

**Comment by shirsig** [comment]
What's a streaming error?

**Comment by dinotheextinct** [comment]
disconnect from wow and "streaming error" I will post a screenshot.

**Comment by dinotheextinct** [comment]
https://imgur.com/a/Z1HuUy0

**Comment by dinotheextinct** [comment]
This can be closed its a Linux related problem regarding anti DDoS protection. When using one of the methods mentioned here: https://www.reddit.com/r/classicwow/comments/d1lncq/reddit_linux_wow_classic_players_are_getting/
The error doesnt happen and the addon successfully does a scan.
