### ISSUE TITLE
Table Full On First Scan

### ISSUE THREAD

**Issue by KevinTyrrell** [shirsig/aux-addon#24]
[Image](http://i.imgur.com/07KPnK8.png)

Is this normal? On my first scan after installing AUX, it claims the table is full. Does that mean the LUA stack is full? StackOverflow? The odd thing is it says the scan will from here on out not save anything but I think it still is saving data. I'm honestly not sure.

**Comment by shirsig** [comment]
The search table size is limited to 1000 for performance reasons. I guess I could go a bit higher but there has to be some limit. If you're doing a historical scan it doesn't matter and otherwise you just have to use a more strict filter to limit the results.

**Comment by KevinTyrrell** [comment]
Perhaps I'm a bit confused. I thought the proper way to use AUX is to, every 24 hours (making sure not to scan within the same 24 period or else you'd get duplicates!) just press the 'search' button with no parameters, that way it scans every page of the auction house and logs their price for that day. You do this day after day after day until a few weeks pass where you have really accurate prices and trends of the auction house. Assuming that is all true, how can the table size get full off of one go?

**Comment by shirsig** [comment]
You can scan as many times per day as you want. Scanning duplicates doesn't make a difference for aux' history. You also don't have to search without parameters. Any page that's scanned for any query will be used for historical data. If you want to scan the whole AH in one scan however you have to make sure you're using an empty blizzard-query. You can read more about that in the main post of the aux thread, but basically blizzard queries are the ones that reduce the number of pages that have to be scanned. Using a post filter like a profit filter for example will still do a scan of all pages.

The search table has nothing to do with the history. It's simply the listing of the search results. If you don't want to buy anything you can ignore the warning. If you're scanning for example linen cloth however and there's so many auctions that more than 1000 would have to be listed then you have to use a more strict filter (for example buyout-pct) to limit the results or the cheapest ones might be among the ones discarded.
