### ISSUE TITLE
No cool UI version for 1.13?

### ISSUE THREAD

**Issue by BBCnewstoday** [shirsig/aux-addon#240]
Hey!
I used aux at 1.12.1 and that was awesome!!!
Any chance to recreate old-styled aux? That was way better and user-friendly than new one.
https://i.imgur.com/HA91s0q.png

**Comment by shirsig** [comment]
No. Why do you think that old version was better?

**Comment by BBCnewstoday** [comment]
Old UI was more intuitive and contrast.
