### ISSUE TITLE
Cannot List Arcane Elixir using Aux

### ISSUE THREAD

**Issue by Diabitus** [shirsig/aux-addon#241]
I've encountered an odd bug, I'm not able to post auction listings for Arcane Elixirs. I have to launch the Blizzard UI for these items. When I select the item from the left window, nothing happens. No scan is done for current market prices, Aux seems to ignore or simply not recognize this item.
-Diabitus

**Comment by shirsig** [comment]
Probably corrupted savedvariables.
Get the newest version and try **/aux clear post** or **/aux clear item cache** and /run ReloadUI()

**Comment by Nimbix-wow** [comment]
you can also use the shorter version of  /run ReloadUI(), **_/rl_**

**Comment by Diabitus** [comment]
Thanks for the replies.

"**/aux clear post**" resolved the issue. Clear Item cache didn't help this particular issue. Uninstalling and reinstalling the addon also didn't help. Good to know in case I hit a similar issue again!
