### ISSUE TITLE
Aux is a problem for raidframe

### ISSUE THREAD

**Issue by sirFAYDE** [shirsig/aux-addon#243]
I noticed that I can’t select some players in blizzard raidframes and occasionally an error appears where exactly Aux is shown. Also on the forum I found out about a wow chat command that shows which addon affects raidframe /run print (issecurevariable ("CompactRaidFrame1")) - in the chat also shows that the problem addon is Aux.
Find out what the problem is and please correct, thanks!
p.s Sorry for my english :)

**Comment by shirsig** [comment]
Is this supposed to be causing an error or something? I'm using **/run print (issecurevariable ("CompactRaidFrame1"))** and it just prints **true nil**
Could it be that you're using an old version?

**Comment by sirFAYDE** [comment]
No, just updated aux today before entering the game. When i using "run print" it prints "False aux-addon"

**Comment by shirsig** [comment]
Ah it was because I'm using elvui, ok, I'll try to fix it tonight.

**Comment by sipertruk** [comment]
There's a possible taint in CompactRaidFrameX from using some functions of UIDropDownMenuTemplate
https://www.wowinterface.com/forums/showthread.php?t=51820

**Comment by sirFAYDE** [comment]
![image](https://user-images.githubusercontent.com/37656345/65711624-f4058300-e09d-11e9-9a3b-c1f456b64c19.png) Here are the error today during the raid

**Comment by sipertruk** [comment]
I could reproduce it by dismissing/summoning a warlock pet in combat while not being in a party or raid, only aux and a debugging addon loaded.
![image](https://user-images.githubusercontent.com/7644041/65716114-cbca5400-e09e-11e9-859f-287470245a9a.png)
Using !NoTaint_UIDropDownMenu fixes the taint in these same testing states.

**Comment by shirsig** [comment]
Thanks all. Unfortunately there doesn't seem to be a simple solution to the tooltip problem (https://www.wowinterface.com/forums/showthread.php?t=51820). Will work on it on the weekend.

**Comment by shirsig** [comment]
Finally fixed it. Decided to just remove all dropdowns from aux in the end.
Most were replaced by a kind of "autocomplete-spinner" and for the favorite searches activating alert and rearranging is done with alt-click and alt-drag.
