### ISSUE TITLE
Regarding /aux scan

### ISSUE THREAD

**Issue by KevinTyrrell** [shirsig/aux-addon#244]
* Is `/aux scan` preferable to pressing the [Search] button with an empty query? Why or why not. What are its limitations?
* Is there any way to access the functionality of `/aux scan` from the GUI? If no, are there plans for a button of some sort? Are there plans to replace empty search queries with the functionality behind `/aux scan` (in other words, instant AH data rather than a 30+ minute scan). Why or why not.
* Is there any notification for when a `/aux scan` completes? Using the most updated version at the moment, the addon informs me it has started to scan, but does not tell me when or if it completes. The only indication I have of the addon scanning is my framerate dropping by a large margin.
* After `/aux scan` seemingly completes (no output message that it did), the tooltips of my items never seen to change (in other words, the market price of the items seems to be unchanged). Why is this and is that working as intended?
* I heard rumors that the API only allows downloading of auction house data every 15 minutes. If this is true, what happens when `/aux scan` is queried again? Should aux output an error message claiming that a repeated scan so soon has no effect?
* If two scans are done in the same 24 period, do auctions from the first scan cause 'duplicate' entries? For example, let's say Item A is posted for 1 gold in the morning. You scan it and aux claims Item A is worth 1 gold. Later that night there are two Item A auctions, one for 1 gold and another for 2 gold. The 1 gold auction is the same one as you scanned in the morning. Therefore, the 'market price' displayed on tooltips should be `(1g + 2g / 2)` where `2` is the number of times aux has seen `Item A`. Is this the case with aux?
* It doesn't appear like Aux has any way of telling the user how many times an auction has been seen total. This causes issues where a user might trust aux's price more than he should. For example, let's say only one [Elemental Mage Staff] has dropped on the server, and the owner posts it for 999 gold. Aux would report its price as 999 gold. However, since aux has only seen [Elemental Mage Staff] once, that price is extremely unreliable. The user will have no idea of this, because aux will simply declare its price as 999 gold. Is this intended design? Are there any ways to query how many times an item has been seen (ignoring duplicates)?

Actually, I did a test of the following:
1) I wrote down the price of four items in my bags. Copper Ore, Greater Healing Potion, Swiftness Potion, and Silk Cloth.
2) I typed `/aux scan`
3) I looked back at the tooltips after the scan completed (again, no message appears that the scan finished, but my framerate went back to normal after 30 seconds). All the items showed the same prices (very unlikely, as prices are likely to have changed very slightly since the last scan days ago)/
4) I typed each items name into the search bar, waited for the scan for that item to complete. After scanning all four items I looked back at the tooltips and they still show the same price.
5) I reloaded my UI, still no change with the tooltips.

Essentially I'm not sure if this means that scanning is completely broken or not or if its just the tooltips?

Thank you for your time.

**Comment by shirsig** [comment]
/aux scan is way faster but it's only for the history currently.
There is a notification in the chat when it begins and when it completes.
It will definitely be added to the UI but I don't know where/how yet.
Empty queries are not using the fast scan setting because fast scans can only be done every 15 minutes and aux does output an error message if you try it again before it's ready.
A scan does not immediately affect the historical value (except on the first day). Only at the end of the day a new daily value is generated which affects the median.
Aux' daily historical values are based on the minimum buyout so it doesn't make a difference how many times you scan the same auction.
It's impossible to say with certainty how many times an auction has been seen because there's no such thing as a unique id for auctions.

**Comment by KevinTyrrell** [comment]
> it's only for the history currently.

Can you explain exactly what you mean by this? To the user we don't see any kind of history for a specific item, only the market value (unless there's some UI that I don't know about). It's not immediately clear what differentiates `/aux scan` from an empty query. They both seem like they lead to the same result (ignoring the 15 minute cooldown and long scan times from empty query).

> It's impossible to say with certainty how many times an auction has been seen because there's no such thing as a unique id for auctions.

Even without ID's, what about if the 'seen' value was only incremented when scans are 24 hours apart. Since all auctions leave the auction house after 24 hours, that means 24 hours later every single auction is unique from your previous scan (and can be counted to a total seen value). Not sure if this is a useless feature or not though. It's quite helpful for items which are not commonly on the auction house.

**Comment by shirsig** [comment]
The difference is that you can't browse the results of /aux scan.
As for the seen value, not sure if it's worth the added complexity. I've thought about such solutions before and I might consider adding it at some point but my time is limited and there are many things with higher priority.

**Comment by KevinTyrrell** [comment]
Minor reply that the Scan button is a wonderful feature. Thank you!
