### ISSUE TITLE
Error 51900319 when posting and searching and looting for specific items

### ISSUE THREAD

**Issue by DavidAlexCarden** [shirsig/aux-addon#245]
Bolt of Woolen Cloth when trying to post is an instant crash
Silk Cloth when scanning
Issues with disconnects during Wailing Caverns - most likely related to certain items dropping.

**Comment by shirsig** [comment]
For the first two issues probably corrupted savedvariables.
Try:
**/aux clear item cache**
**/aux clear post**
**/run ReloadUI()**

**Comment by Havenloft** [comment]
1x aux-addon\tabs\post\core.lua:56: attempt to index global 'selected_item' (a nil value)
aux-addon\tabs\post\core.lua:56: in function `get_buyout_selection'
aux-addon\tabs\post\frame.lua:109: in function `selected'
aux-addon\gui\listing.lua:29: in function <aux-addon\gui\listing.lua:26>

Locals:
(*temporary) = <table> {
 4306:0 = <table> {
 }
 4338:0 = <table> {
 }
 5117:0 = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to index global 'selected_item' (a nil value)"
buyout_selections = <table> {
 4306:0 = <table> {
 }
 4338:0 = <table> {
 }
 5117:0 = <table> {
 }
}

**Comment by Crisdmc** [comment]
Message: Interface\AddOns\aux-addon\util\money.lua:61: attempt to compare nil with number
Time: Sat Sep 28 11:47:43 2019
Count: 4
Stack: Interface\AddOns\aux-addon\util\money.lua:61: attempt to compare nil with number
[C]: ?
Interface\AddOns\aux-addon\util\money.lua:61: in function `to_string'
Interface\AddOns\aux-addon\tabs\post\core.lua:406: in function `update_item'
Interface\AddOns\aux-addon\tabs\post\frame.lua:63: in function <Interface\AddOns\aux-addon\tabs\post\frame.lua:61>

Locals:

**Comment by Crisdmc** [comment]
I used
/aux clear item cache
/aux clear post
/run ReloadUI()

It kinda worked, the price for the post was wrong, 2H had the 8H price, so I opened the blizz UI to check, and aux was broken again:

Message: Interface\AddOns\aux-addon\util\money.lua:61: attempt to compare nil with number
Time: Sat Sep 28 11:52:48 2019
Count: 10
Stack: Interface\AddOns\aux-addon\util\money.lua:61: attempt to compare nil with number
[C]: ?
Interface\AddOns\aux-addon\util\money.lua:61: in function `to_string'
Interface\AddOns\aux-addon\tabs\post\core.lua:406: in function `update_item'
Interface\AddOns\aux-addon\tabs\post\frame.lua:63: in function <Interface\AddOns\aux-addon\tabs\post\frame.lua:61>

Locals:

**Comment by Crisdmc** [comment]
I downloaded the github project RN, its working again, just the 2H and 8H text are wrong, not the price... Is showing [8H, 2H, 24H]

**Comment by shirsig** [comment]
There was a bug that the price got corrupted if something invalid was entered. I fixed that so hopefully this will not occur anymore.
