### ISSUE TITLE
Error on Classic:

### ISSUE THREAD

**Issue by Havenloft** [shirsig/aux-addon#246]
1x [ADDON_ACTION_BLOCKED] AddOn 'aux-addon' tried to call the protected function 'CompactRaidFrame2:SetAttribute()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetAttribute'
FrameXML\CompactUnitFrame.lua:161: in function `CompactUnitFrame_SetUnit'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:318: in function `CompactRaidFrameContainer_AddUnitFrame'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:254: in function `CompactRaidFrameContainer_AddPlayers'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:176: in function `CompactRaidFrameContainer_LayoutFrames'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by shirsig** [comment]
There's already an issue for this: https://github.com/shirsig/aux-addon/issues/243
