### ISSUE TITLE
Post Button Grayed Out

### ISSUE THREAD

**Issue by JosephKrusling** [shirsig/Aux-Addon#25]
The button to post a new auction is always gray and disabled for me. I've tried deleting the saved variables files, but with no luck. I'm not using any other auction addons or addons that modify tooltips. I've also tried using /aux clear post but that doesn't do anything for me. What should I do? Here's a list of all the addons I'm using 
![image](https://cloud.githubusercontent.com/assets/4973501/14948199/b5d509ae-100b-11e6-8e66-3c6e4f75560e.png)

**Comment by shirsig** [comment]
Are you using a starting price than buyout or a starting price of 0?

**Comment by JosephKrusling** [comment]
Yes, I feel like an idiot. :P 
Thanks for the quickly reply
