### ISSUE TITLE
Undercut for starting bids is doing weird things

### ISSUE THREAD

**Issue by Winsane** [shirsig/aux-addon#250]
The automatic undercut for starting bid (When using /aux post bid) is not working correctly, I think. The values make no sense, and the price per unit is changing depending on what stack size you set.

In tabs/post/core.lua at line 195:

`set_unit_start_price(undercut(get_bid_selection() or get_buyout_selection(), stack_size_slider:GetValue(), get_bid_selection()))`

I don't understand why it passes get_bid_selection() at the end, and it seems to be an error(?)

Removing the get_bid_selection() at the end results in what I would assume is the intended behavior.

**Comment by Altoholic** [comment]
`Harpner linked a pull request that will close this issue on 26 Mar 2020`

Can we have it now ? ^^

**Comment by shirsig** [comment]
As I've explained many times, this is not a bug.
Maybe I will add an additional option for unit bid undercutting so people stop complaining.

**Comment by shirsig** [comment]
There is **/aux post bid unit** now
