### ISSUE TITLE
Error when trying to post Mageweave

### ISSUE THREAD

**Issue by antitheseus** [shirsig/aux-addon#255]
Hi, 
I get this error -only- when clicking on the Mageweave icon in the post tab or drag and drop it from bag.
Other addons are disabled. Doesn't happen with any other item.

 `Message: Interface\AddOns\aux-addon\util\money.lua:61: attempt to compare nil with number
Time: Wed Oct  2 13:32:09 2019
Count: 1
Stack: Interface\AddOns\aux-addon\util\money.lua:61: attempt to compare nil with number
Interface\AddOns\aux-addon\util\money.lua:61: in function `to_string'
Interface\AddOns\aux-addon\tabs\post\core.lua:406: in function `update_item'
Interface\AddOns\aux-addon\tabs\post\frame.lua:63: in function <Interface\AddOns\aux-addon\tabs\post\frame.lua:61>

Locals: money = nil
pad = true
trim = nil
color = nil
no_color = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
aux = <table> {
}`

**Comment by shirsig** [comment]
It's corrupted savedvariables. **/aux clear post** will fix it
