### ISSUE TITLE
New Filter Builder sucks.

### ISSUE THREAD

**Issue by padmanek** [shirsig/aux-addon#256]
Having to click up/down arrow to find your desired category is just waste of time/clicks. If it was at least scrollable ..but it's not. It just zooms in/out the camera.
If you want to make a tiny adjustment to your recent filter then you have to select everything all over again since it doesn't save last selections.
Bad UI design decision. Please bring back the drop down menu.
People on CurseForge already saying they're reverting to the old version. 
https://www.curseforge.com/wow/addons/aux?comment=168
https://www.curseforge.com/wow/addons/aux?comment=172
https://www.curseforge.com/wow/addons/aux?comment=162

**Comment by shirsig** [comment]
It's  been explained over and over... I didn't remove the dropdowns because I like spinners more but because the blizzard dropdowns cause taint errors which make the default raidframes unusable and there is no workaround besides implementing your own dropdowns which will take time.

Also it seems you haven't realized that you can type in the boxes with autocomplete which is usually faster than a dropdown anyway.

**Comment by padmanek** [comment]
What about not saving the latest chosen options in the builder? When I select lets say (Armor Leather Chest Uncommon and some level range) and look for some upgrades for my alt and then I want to switch it to Head instead then I have to select everything all over again. It was all saved in 0.4.10 build with old drop down list.

**Comment by shirsig** [comment]
Wasn't aware I changed that but as long as you have the query in the searh box you can always get it back with the import button.

**Comment by mooreatv** [comment]
@padmanek pro tip: when you're asking something from someone spending their time working for free to make your gaming experience better, try to not use language like "... sucks" it's very rude and inconsiderate and doesn't really make people want to help you (but shirsig is a saint and he is doing it anyway!)

**Comment by padmanek** [comment]
> @padmanek pro tip: when you're asking something from someone spending their time working for free to make your gaming experience better, try to not use language like "... sucks" it's very rude and inconsiderate and doesn't really make people want to help you (but shirsig is a saint and he is doing it anyway!)

"sucks" is not at all an offensive word and is used very often in common speak but I guess you're not a native english speaker. If an adult said "it sucks", it would be acceptable in most informal settings.
