### ISSUE TITLE
Filter settings are not remembered since update + New users can't learn post filter options

### ISSUE THREAD

**Issue by adexxoda** [shirsig/aux-addon#257]
Before the last update, search settings (level range, item class, component) were remembered when going back to the filter builder after a search. Now only the component part with the post filters is remembered. Some error probably happened when the dropdown-menu was changed to the arrow-style selection, unless this is intended behaviour.

For the post filters however, the dropdown-list was not replaced with the arrows, there simply isn't anything else besides the textbox anymore. This makes it impossible for new users to learn the terms that can be used. I'd suggest adding arrows to click through the possible options, or return the dropdown-list, which makes it easier to compare the options and have an overview.

I generally prefered the dropdown-lists anyway as they felt faster, but that may be personal taste.

Edit: I just saw now that there was already a post about this, sorry about that! Makes sense to change it if the dropdown-menus broke something else. However, new users still can't learn the post filter commands this way unless I missed something.

**Comment by shirsig** [comment]
fixed, and there are dropdowns again too, made my own implementation.
