### ISSUE TITLE
Full auction scan when trying to post Fused Wiring

### ISSUE THREAD

**Issue by refaim** [shirsig/aux-addon#258]
I'm playing the Russian version of a game client and using aux 0.5.10. When I try to post Fused Wiring ("Кабельная система с плавкими предохранителями" in russian), aux starts to scan the whole auction instead of searching for this particular item.

Also when I try to search for `кабельная система с плавкими предохранителями/exact` aux starts searching for `tooltip/кабельная система с плавкими предохранителями/exact` instead of `[Кабельная система с плавкими предохранителями]`. It also leads to the full auctions scan.

**Comment by shirsig** [comment]
Strange bug. Could have to do with some lua regex patterns only working for latin characters, but then I would expect this to happen for all russian searches ... I'll look into it on the weekend.

**Comment by shirsig** [comment]
fixed.
