### ISSUE TITLE
Can't put multiple stacks on the AH

### ISSUE THREAD

**Issue by luxlime** [shirsig/aux-addon#259]
Addon is working flawless, 

but i cant put multiple stacks of any item on the AH.
especially when i want to put 20 stacks of 1, i have to click it 20 times. Is there a way in the options, to sell multiple stacks with just one click?

Greetz
lux

**Comment by shirsig** [comment]
It seems it can even be done for multiple inventory stacks with the API, at least it worked now the last time I tested it, but it still seems unreliable and doesn't always finish. Not sure if it's lag related, will have to investigate more. Anyway, this is the next thing on the roadmap for aux.

**Comment by shirsig** [comment]
This is working now.
