### ISSUE TITLE
Page Count Not Showing In Status Bar

### ISSUE THREAD

**Issue by Patchett** [shirsig/aux-addon#260]
As of the latest update, the page count is no longer showing in the bottom left corner of the aux frame. Take note in the below screenshot:

https://puu.sh/EpqWK/c4e309da8f.png

**Comment by shirsig** [comment]
This is intended.

**Comment by Patchett** [comment]
@shirsig why is this intended? I really liked this feature. It gave me a great idea of how healthy the economy is on the server. TSM shows the number of auction on the AH. The number of pages in Aux provided a similar metric. Now aux has nothing like that. This pagination has been there since the nost days man. Please don't remove it

**Comment by shirsig** [comment]
I think it looks better without text, and it's more consistent with the getall scan which has only one page. Anyway, why are the exact numbers important? You can still see how much there is approximately from the progress bar. The numbers are too technical I think. I think I'llalso remove the page range inputs for the regular scan and make it always full. I don't remember why I added them even, maybe for bid wars since the bids tab wasn't refreshing properly in 1.12.

**Comment by Patchett** [comment]
The exact numbers allow me to gauge how the auction house and the economy breathes throughout the day and night. When are the peeks, when are the valleys. It allows me to know when the market is saturated vs not saturated just by hitting scan and glancing at the page numbers. It also allows me to make characters on other servers and compare the size of their faction and the health of their economy with ours. This is especially useful since /who is now a protected command and things like census plus no longer work. Checking the size of the auction house is now really the only way to get a numerical representation of the economy and population on a server.

Most of your users here are power users. And the majority of your users are from private servers. Everyone wants to see the numbers. The retail people are all using TSM/Auctioneer. I am sticking with Aux despite being tempted because I know you work hard on this addon and I have been using it now for like 4 years. At least give us a toggle option to turn it on or something. Or better yet just put it back :)

**Comment by shirsig** [comment]
Aux was never meant for power users, quite the opposite, it's supposed to allow users to use the basic functions of the ah as simply and efficiently as possible without being ripped off. If I wanted to play the AH I would probably use TSM or something myself.

Further I would be surprised if even 5 other people use the numbers in the way you described, let alone "everyone".

Anyway, to get these numbers you don't need any AH addon, a simple macro is enough. Make a filterless search in aux (or the default AH) and then run **/run print(select(2, GetNumAuctionItems'list'))** to get the total number of auctions.
