### ISSUE TITLE
Request: Sort By Bidding %?

### ISSUE THREAD

**Issue by lystig12** [shirsig/aux-addon#266]
To my understanding, "% Hist. Value" is based on (of course) the historical of the item + the current buyout price for a single item (irregardless of the stack size of the auction).

If I sort ascending on "% Hist. Value", the auctions will be listed according to "most bang for your buck if you choose to use the **buyout** function".

However, more often than not the bid-buyout gap is significantly different across the different listings of a given item. If I'm interested in finding good "bid deals", I currently don't have a good way of sorting the auctions to list them according to "most bang for your buck if you choose to use the **bid** function".

Would it be possible to add a sort that is based on the bid price which would help me find good bid deals?

**Comment by shirsig** [comment]
In the latest version you can right click the percentage column like the price columns to toggle between bid and buyout.
