### ISSUE TITLE
post tab lua error

### ISSUE THREAD

**Issue by mooreatv** [shirsig/aux-addon#267]
I did the clear post and clear item cache but

1x aux-addon\util\info-Info.lua:39: attempt to index local 'item_info' (a nil value)
aux-addon\util\info-Info.lua:39: in function `container_item'
aux-addon\tabs\post\core.lua:433: in function `update_inventory_records'
aux-addon\tabs\post\core.lua:89: in function `pass'
aux-addon\aux-addon-0.7.2.lua:117: in function <aux-addon\aux-addon.lua:114>
aux-addon\gui\core.lua:171: in function `select'
aux-addon\gui\core.lua:146: in function <aux-addon\gui\core.lua:143>

Locals:
bag = 0
slot = 2
link = "|cffffffff|Hitem:3456::::::::42:::1::::|h[]|h|r"
item_id = 3456
suffix_id = 0
unique_id = 0
enchant_id = 0
item_info = nil
texture = 132161
count = 1
locked = false
quality = -1
readable = false
lootable = false
durability = nil
max_durability = nil
tooltip = <table> {
 1 = "Retrieving item information"
}
auctionable = true
max_charges = nil
charges = nil
aux_quantity = 1
(*temporary) = <table> {
 item_key = "3456:0"
 item_id = 3456
 enchant_id = 0
 link = "|cffffffff|Hitem:3456::::::::42:::1::::|h[]|h|r"
 unique_id = 0
 suffix_id = 0
}
(*temporary) = "3456:0"
(*temporary) = ":"
(*temporary) = "0"
(*temporary) = "attempt to index local 'item_info' (a nil value)"

**Comment by shirsig** [comment]
You need to do /run ReloadUI() also

**Comment by mooreatv** [comment]
I did reload and log out even a few times to no avail

**Comment by shirsig** [comment]
Then I don't know what it could be. Try deleting the whole savedvariables.

**Comment by alexdoub** [comment]
Happens to me when trying to post fadeleaf or ghost mushroom

```
Message: Interface\AddOns\aux-addon\util\money.lua:62: attempt to compare nil with number
Time: Tue Oct 22 07:41:05 2019
Count: 1
Stack: Interface\AddOns\aux-addon\util\money.lua:62: attempt to compare nil with number
Interface\AddOns\aux-addon\util\money.lua:62: in function `to_string'
Interface\AddOns\aux-addon\tabs\post\core.lua:401: in function `update_item'
Interface\AddOns\aux-addon\tabs\post\frame.lua:63: in function <Interface\AddOns\aux-addon\tabs\post\frame.lua:61>

Locals: money = nil
pad = true
trim = nil
color = nil
no_color = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
T = <table> {
}
aux = <table> {
}

```

**Comment by alexdoub** [comment]
Fixed it by deleting the aux SavedVariable data in
`C:\Games\World of Warcraft\_classic_\WTF\Account\<your account>\SavedVariables\aux-addon.lua`
