### ISSUE TITLE
Stack count resets while posting

### ISSUE THREAD

**Issue by tyggyr** [shirsig/aux-addon#268]
While I appreciate the addon's gaining a "Stack Count" slider, I was surprised to find that after setting eg (stack size = 1, stack count = 1) that immediately thereafter the "Stack Count" slider moved back to the maximum. Is this intended behavior? Coming from my prior use without the stack count slider (ie, stack count per post was fixed at 1), I found myself immediately posting the remainder of my items instead of just another 1 as the previous "post" operation had done. Obviously, I'll get used to the behavior (don't have to post multiple times, nice) but I still think that this violated the principle of least surprise.

**Comment by shirsig** [comment]
Yes, that's intended and I think it was working like that in aux on private servers.
