### ISSUE TITLE
TBC Version

### ISSUE THREAD

**Issue by cnolimes** [shirsig/aux-addon#27]
Are You planning to make it compatible with 2.4.3 WoW ?

**Comment by shirsig** [comment]
Not for now, sorry, I've looked at it and it breaks too much. Maybe if I have time during the semester break.

**Comment by kochetkovd** [comment]
we will wait for compatibility with TBС. Thank you =)

**Comment by CptKiwi** [comment]
Would love a TBC release.
It looks like an awesome addon

**Comment by shirsig** [comment]
I'm afraid it's probably never gonna happen. I've even kinda gone in the other direction and started to add more vanilla features which wouldn't be possible in TBC (sniping with automatic buyout for example) and also in lua there were tons of changes. I would say TBC lua is more similar to retail lua than it is to vanilla lua.

**Comment by cnolimes** [comment]
A moment of silence for the loss!
