### ISSUE TITLE
Disenchant-Profit filter calculates wrong profit

### ISSUE THREAD

**Issue by Und3adrav3n** [shirsig/aux-addon#270]
In official wow Classic:
first of all i scan the AH to update the addon databese with fresh values
I create a filter like this: armor/uncommon/disenchant-profit/30s
The scan presents me an item (cloth rare head) with a 100% chance to disenchant in Large Radiant Shard, this item buyout is 2g
If i look the AH for a Large Radiant Shard i can find them with buyout of 1g95s and so on so the "expected" profti of 30s is wrong
This is an exemple but it happens often, is there a bug in the "value" calculation or in the item's "disenchant table"? 
I reported this example because the "value" calculation isn't involving probability (100% Large Radiant Shard) so may help you more; tell me if i can provide more useful informations

**Comment by shirsig** [comment]
The profit is based on the historical value, not what's currently on the AH.
