### ISSUE TITLE
Listing multiple recipes

### ISSUE THREAD

**Issue by fgsfdss** [shirsig/aux-addon#271]
Attempting to list multiple of the same recipe results in the "You do not have enough items." error each time. Works fine if you reduce stack count to 1 and do it manually.

![image](https://user-images.githubusercontent.com/5033279/68044408-8faa9480-fcd7-11e9-8f5d-c34019e0990b.png)

**Comment by shirsig** [comment]
Strange. I tried it with some other cheap recipe and it worked fine. Also, this error is not from aux directly but from the blizzard api. The only thing that could go wrong on aux' side is that it selects the wrong item for posting but I don't see how it could break only for this specific item ...

**Comment by fgsfdss** [comment]
Found the same issue when posting Discombulator Rays. They list in a stack of 5 (5 charges) but always give the error when attempting to list. For this item, in fact, it is impossible to list it as a single stack count, as it will always recognise as a 5-stack.
![image](https://user-images.githubusercontent.com/5033279/69015075-cdbede00-0990-11ea-8dda-a952bbf1fe63.png)
I have to thus list these via the Blizzard UI.

**Comment by shirsig** [comment]
Fixed the second issue for charge items but that was something else. Note that aux treats charges the same as stacks in the UI so you have to post as stack size 5 for example if it has charges.
