### ISSUE TITLE
LUA error when posting many items

### ISSUE THREAD

**Issue by GregoryGH** [shirsig/aux-addon#274]
It seems always get this error when posting many different items in one session

1x aux-addon\tabs\post\core.lua:74: attempt to index global 'selected_item' (a nil value)
aux-addon\tabs\post\core.lua:74: in function `get_buyout_selection'
aux-addon\tabs\post\frame.lua:109: in function `selected'
aux-addon\gui\listing.lua:29: in function <aux-addon\gui\listing.lua:26>

Locals:
(*temporary) = <table> {
 15927:0 = <table> {
 }
 2672:0 = <table> {
 }
 2886:0 = <table> {
 }
 7075:0 = <table> {
 }
 5504:0 = <table> {
 }
 858:0 = <table> {
 }
 5635:0 = <table> {
 }
 5498:0 = <table> {
 }
 1081:0 = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to index global 'selected_item' (a nil value)"
buyout_selections = <table> {
 15927:0 = <table> {
 }
 2672:0 = <table> {
 }
 2886:0 = <table> {
 }
 7075:0 = <table> {
 }
 5504:0 = <table> {
 }
 858:0 = <table> {
 }
 5635:0 = <table> {
 }
 5498:0 = <table> {
 }
 1081:0 = <table> {
 }
}

**Comment by shirsig** [comment]
Should be fixed now.
