### ISSUE TITLE
Disconnecting during full scan

### ISSUE THREAD

**Issue by SwimmingTiger** [shirsig/aux-addon#275]
When I click the scan button and go halfway through it, I always disconnect from the server. Need a scanning speed limiter like Auctionator's.

https://github.com/Auctionator/Auctionator/wiki/Disconnecting-During-Full-Scan

> # Disconnecting During Full Scan
> Auctionator has a rate limiter as part of its full scan. Changing the value of that rate limiter might prevent your disconnection. To change the value type in chat `/atr fsc 40`. That will change the rate limiter value from the default of 50 to 40. If that doesn't work you can try lower values. This change is sticky - you don't have to do it every time you log in.

Consider applying the speed limiter only for full scans to prevent slower normal scans.

**Comment by shirsig** [comment]
I've throttled a bit. Does it still disconnect you?

**Comment by SwimmingTiger** [comment]
No more disconnecting. thank you.
