### ISSUE TITLE
Multi-category queries

### ISSUE THREAD

**Issue by KevinTyrrell** [shirsig/aux-addon#276]
I've never seen an auction house addon that does this, so I assume its impossible.

It'd be nice to be able to type in more dynamic queries. For example.

* Swords or Axes with the name 'of the monkey'. (meaning no other weapons besides swords and axes appear in the result set)
* Cloth, Leather, or Mail helmets of blue quality or higher.
* Epic Items or Blue Items with a ilvl >= 50
* 'of the Fiery Wrath', filter only based on the items a mage can use (staff, dagger, sword, held in offhand, cloth armor)

All of these types of queries are not possible with the current verison of aux. The string users type in for queries seems like it can adapt to this functionality. Perhaps there could be an 'advanced search' where users could check boxes of all of the categories that they would want in their query.

**Comment by shirsig** [comment]
Of course it's possible. You have to use semicolons to separate multiple blizzard queries.
