### ISSUE TITLE
Item quality on recent searches

### ISSUE THREAD

**Issue by spidor** [shirsig/aux-addon#277]
Since the last patch item quality in the recent searches messed up, and shows everything (almost) as legendary quality. 

![aux_scr](https://user-images.githubusercontent.com/3750480/68939825-d7362380-07a1-11ea-9639-ffe1b5f2f010.jpg)

**Comment by shirsig** [comment]
Hey. That it is the same color as legendary is coincidental. Orange is just the default color for all operators. This happens when there is no item data for the items in the query. I guess you have deleted your savedvariables recently or used /aux clear item data or something? Eventually the item data should all be back but this can take like an hour of playtime or more I guess.

**Comment by spidor** [comment]
Interesting, because I'm sure there were items on the AH from the recent searches list. It has been like this since the last update, that is why I thought it was changed in the patch.

**Comment by shirsig** [comment]
I think the auction api does not automatically fetch the data for the iteminfo api. If you called **/run GetItemInfo(id)** with the id of one of these items then after a second do another search then the item should have the correct color. Or you can wait for aux to fetch it which may take a while because it starts with item id 1 and goes up to 15k or something and it is quite throttled.

**Comment by spidor** [comment]
Thanks for the tip. Unfortunately it didn't work. I also tried to totally reinstall the addon. Deleted my saved variables, restored them, didn't work either. 
It is not a big deal, but helps to overview the items easier. Also I noticed that the auto-completion is working a little weird. It does not give me suggestions, and if I remember correctly it did before. Could be those two issues connected? 
Anyway, thanks for your help.

**Comment by shirsig** [comment]
Are you sure? Like I said, it may take a while for aux to scan the item data again. If it's a high item id possibly hours. And you have to be careful not to kill the client but exit normally or savedvariables will never be saved.

**Comment by spidor** [comment]
Should I just let Aux run while the AH window is open or is there anything else I should do?

**Comment by shirsig** [comment]
You don't need to be at the ah.

**Comment by E1ila** [comment]
Is there a way to know aux is still querying item info, or has finished?

**Comment by spidor** [comment]
> Is there a way to know aux is still querying item info, or has finished?

That's a good question. Over the weekend I was online for hours continuously and logged out  properly every time. Yet the issue is still exists.

**Comment by shirsig** [comment]
No. It shouldn't really affect you besides autocompletion and displaying of the queries though and it doesn't require any action from you so you can just keep playing normally and after a few days all items should be fetched.

Improving the fetch time is the next thing on my todo list for aux, but it's gonna be difficult as I have to throttle it enough that people aren't disconnected and I think there are different thresholds for different regions.

**Comment by shirsig** [comment]
> > Is there a way to know aux is still querying item info, or has finished?
> 
> That's a good question. Over the weekend I was online for hours continuously and logged out properly every time. Yet the issue is still exists.

I'll check it out, maybe there's also a bug.

**Comment by spidor** [comment]
> I'll check it out, maybe there's also a bug.

Thank you very much :)

**Comment by shirsig** [comment]
Indeed there was a bug. Fixed it now and it's working like before. Still planning to optimize it as it is pretty slow.

**Comment by spidor** [comment]
> Indeed there was a bug. Fixed it now and it's working like before. Still planning to optimize it as it is pretty slow.
> 
> Edit: faster item scanning, only on github for now, might cause lags or disconnects.

Awesome, thank you for checking and fixing it :) I'll give the github version a try, and let you know my results.

**Comment by spidor** [comment]
It is working for me now. Interestingly I thought it would start querying the items by itemID lower to higher, but it seems not. Anyway as you can see the Arcanite Bar is now queryed properly, so I quess it just need more time to finish every item :) 

![WoWScrnShot_112019_095806](https://user-images.githubusercontent.com/3750480/69224397-c3f9ce00-0b7c-11ea-9bdd-23b5ff056570.jpg)


I'll be using aux more in the next few days. Do you want me to report my results?

**Comment by shirsig** [comment]
Yeah, please.

**Comment by spidor** [comment]
> Yeah, please.
It's working as it worked before the bug report. Items are queried. I got a few disconnects, but really just 2-3 times.

**Comment by shirsig** [comment]
These disconnects were soon after logging in or could also have been for other reasons? Because with this speed the scanning shouldn't take more than a few minutes.

**Comment by spidor** [comment]
No, disconnects seems to be random, not short after logging in. I've been online for few hours, and there are still items that are not queried, so it takes more than just a few minutes. Not sure how many items are queried thought, but most of my recent searches are.

**Comment by shirsig** [comment]
I think they they weren't working was a different bug. It really should've been finished within 10 minutes or so at that speed. Anyway, I still added some throttling to be safe and put it on curse now.
