### ISSUE TITLE
[bug report] : /aux post duration don't work.

### ISSUE THREAD

**Issue by Altoholic** [shirsig/aux-addon#280]
I put it on 8h, but it seem to be randomly chosen each time.

**Comment by shirsig** [comment]
Could be a savedvariables issue. Also, note that for each item the last duration used is saved, so unless you've never posted an item this setting will be ignored.

**Comment by Altoholic** [comment]
Ok. Could we make it otherwise ? If a post duration is chosen, it supersede the last duration, and if no post duration is chosen, the last duration is used ?

**Comment by shirsig** [comment]
I think it makes more sense this way, but if you want to clear your existing settings you can do it with **/aux clear post**
