### ISSUE TITLE
Discombobulator Ray (Items w/ Charges)

### ISSUE THREAD

**Issue by KevinTyrrell** [shirsig/aux-addon#281]
The item Discombobulator Ray (and perhaps all items with charges) behaves strangely inside of Aux. 

In this example, I have 2 Discombobulator Rays each with 5 charges. Aux reports that as me having 10 Discombobulator Rays.

![image](https://user-images.githubusercontent.com/12791400/71207674-6937bd00-2275-11ea-8a07-dc6a40ca9e8e.png)

If I drag the slider to post in stacks of 1 (Discombobulator Rays can only stack in stacks of 1), it reports the stack count as 0, which is dangerous and could potentially lead to div/0 errors.

![image](https://user-images.githubusercontent.com/12791400/71207889-dea38d80-2275-11ea-8a05-af91e519136e.png)

If I attempt to post the Discombobulator Ray which has 5 charges to the auction house at a unit price of 2g95s99c it will post for 14g79s95c, as it thinks the charges are the stack quantity.

**Comment by shirsig** [comment]
This is intended and it's been like that for a long time. Makes things simpler and more consistent with regard to the unit price, because of course an item with one charge is worth less than one with 5.

**Comment by KevinTyrrell** [comment]
> 
> 
> This is intended and it's been like that for a long time. Makes things simpler and more consistent with regard to the unit price, because of course an item with one charge is worth less than one with 5.

Fair enough, however the stack count should never reach zero, as that would imply that I'm about to post zero stacks which is not true.

Perhaps add a `max( ..., 1)` to the formula calculating stack count.

**Comment by shirsig** [comment]
Isn't the post button disabled when it's 0?

**Comment by shirsig** [comment]
It's seems it's not possible to post items with less than max charges (anymore?). Aux was treating charges like stack size because it was possible on private servers, but now this seems pointless, so I removed it.
