### ISSUE TITLE
lua Errors in latest version

### ISSUE THREAD

**Issue by smoothys** [shirsig/aux-addon#289]
Sometimes when logging into game and always when /aux

Message: Interface\AddOns\aux-addon\core\slash.lua:69: attempt to concatenate a nil value
Time: Fri Mar 13 07:34:27 2020
Count: 1
Stack: Interface\AddOns\aux-addon\core\slash.lua:69: attempt to concatenate a nil value
Interface\AddOns\aux-addon\core\slash.lua:69: in function `?'
Interface\FrameXML\ChatFrame.lua:4690: in function <Interface\FrameXML\ChatFrame.lua:4637>
[C]: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4351: in function <Interface\FrameXML\ChatFrame.lua:4350>
[C]: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4387: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: command = ""
arguments = <table> {
}
tooltip_settings = <table> {
 merchant_buy = false
 merchant_sell = true
 value = true
 disenchant_distribution = false
 disenchant_value = false
 daily = true
}
(*temporary) = <function> defined @Interface\AddOns\aux-addon\aux-addon.lua:5
(*temporary) = "- post duration ["
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = "h"
(*temporary) = "attempt to concatenate a nil value"
aux = <table> {
}
post = <table> {
}
info = <table> {
}

**Comment by shirsig** [comment]
You mean it's only been happening since yesterday? That's strange since there was no code change. I only changed the client version. Could be because of something blizzard changed in that patch though I guess.

**Comment by smoothys** [comment]
Yeah I updated this morning to the latest version, and  I currently have /console scriptErrors 1 turned on.

**Comment by shirsig** [comment]
it looks like a savedvariables issue.
