### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Altoholic** [shirsig/aux-addon#295]
I don't see "aux" here, but as i was at the AH, i suppose it's related.

2x ...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:1129: attempt to index local 'color' (a nil value)
...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:1129: in function `AuctionFrameBid_Update'
...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:1064: in function <...aceBlizzard_AuctionUI\Blizzard_AuctionUI.lua:1062>

Locals:
numBatchAuctions = 14
totalAuctions = 14
button = BidButton2 {
 0 = <userdata>
 itemCount = 1
 buyoutPrice = 80000
 bidAmount = 110
}
buttonName = "BidButton2"
buttonHighlight = BidButton2Highlight {
 0 = <userdata>
}
iconTexture = BidButton1ItemIconTexture {
 0 = <userdata>
}
itemName = BidButton2Name {
 0 = <userdata>
}
color = nil
itemCount = BidButton1ItemCount {
 0 = <userdata>
}
offset = 0
index = 2
isLastSlotEmpty = nil
name = ""
texture = nil
count = 1
quality = -1
canUse = false
level = -1
levelColHeader = nil
minBid = 2000
minIncrement = 100
buyoutPrice = 2800
bidAmount = 2000
highBidder = true
bidderFullName = nil
owner = "Furyy"
ownerFullName = nil
itemID = 11370
_ = 0
duration = 3
(for index) = 2
(for limit) = 9
(for step) = 1
i = 2
(*temporary) = <function> defined =[C]:-1
(*temporary) = BidButton2Name {
 0 = <userdata>
}
(*temporary) = ""
(*temporary) = <userdata>
(*temporary) = false
(*temporary) = -1
(*temporary) = nil
(*temporary) = 2000
(*temporary) = 100
(*temporary) = 2800
(*temporary) = 2000
(*temporary) = true
(*temporary) = nil
(*temporary) = "Furyy"
(*temporary) = nil
(*temporary) = 0
(*temporary) = 11370
(*temporary) = "attempt to index local 'color' (a nil value)"

**Comment by shirsig** [comment]
I don't know, these are not aux frames, and **ace**Blizzard_AuctionUI this looks like another addon to me.

**Comment by Altoholic** [comment]
Ok. I can't find that Blizzard_AuctionUI.lua file in my addons anyway, and the error did not happen again, so maybe something was updated, or i get rid of the culprit without knowing.
