### ISSUE TITLE
[suggestion] armor slot search without armor type

### ISSUE THREAD

**Issue by goudekid** [shirsig/aux-addon#296]
It'd be nice if a query didn't contain an armor type, it'd automagically create a compound and behind the scenes that amalgamates all the armor types

ex: you query "armor/hands/52/60/strength" 

but what actually gets searched is 

"armor/plate/hands/52/60/strength;armor/mail/hands/52/60/strength;armor/leather/hands/52/60/strength;armor/cloth/hands/52/60/strength"

**Comment by shirsig** [comment]
Not sure if it's possible with this api. It was possible in vanilla aux and I remember removing it but not sure if it was because it was impossible or because it required too many changes and I had not enough time.

**Comment by shirsig** [comment]
Double checked and it doesn't seem to be possible with the new api.
