### ISSUE TITLE
[bug report] incomplete piles can't be posted after posting completes piles

### ISSUE THREAD

**Issue by Altoholic** [shirsig/aux-addon#299]
The post button become gray, and an error message appear : https://imgur.com/a/TW4TbfN

You have to reload the UI each time after that.

The bug is 100% reproducible.

Edit: this bug appeared with the update of today.

**Comment by shirsig** [comment]
How do you reproduce it?

**Comment by shirsig** [comment]
Nevermind, I found the issue. It happened when posting with a stack size that leaves a remainder.

**Comment by shirsig** [comment]
Just realized I should've read the title of the bug report xD
