### ISSUE TITLE
Issue related to search order.

### ISSUE THREAD

**Issue by mateszbukaty** [shirsig/aux-addon#30]
I've encountered something weird today. I thought something was bugged with searching some herbs (namely Peacebloom and Silverleaf) in situations where I was searching for a larger number of different herbs at once. However, I've done some more testing and right now I think the issue lies elsewhere.

## The experiment:
**Search terms:**
Peacebloom;Silverleaf;Earthroot;Mageroyal;Swiftthistle;Briarthorn;Stranglekelp;Bruiseweed;Wild Steelbloom;Grave Moss;Kingsblood
**Outcome:**
Peacebloom, Silverleaf.
**Screenshot:** http://i.imgur.com/bptUtXY.png

**Search terms:**
Silverleaf;Peacebloom;Earthroot;Mageroyal;Swiftthistle;Briarthorn;Stranglekelp;Bruiseweed;Wild Steelbloom;Grave Moss;Kingsblood
**Outcome:**
Peacebloom, Silverleaf.
**Screenshot:** http://i.imgur.com/2v9e6bz.png

**Search terms:**
Stranglekelp;Peacebloom;Silverleaf;Earthroot;Mageroyal;Swiftthistle;Briarthorn;Bruiseweed;Wild Steelbloom;Grave Moss;Kingsblood
**Outcome:**
Peacebloom, Silverleaf, Stranglekelp.
**Screenshot:** http://i.imgur.com/MJow9gf.png

**Search terms:**
Earthroot;Mageroyal;Swiftthistle;Briarthorn;Stranglekelp;Bruiseweed;Wild Steelbloom;Grave Moss;Kingsblood;Peacebloom;Silverleaf
**Outcome:**
Peacebloom, Silverleaf, Bruiseweed, Mageroyal, Earthroot, Kingsblood, Stranglekelp, Swiftthistle, Wild Steelbloom, Briarthorn; Grave Moss
**Screenshot:** http://i.imgur.com/mUaILRQ.png

## Observation:
In situations where you search for multiple items, separated with ";", whenever Aux finds something that has more than 50 auctions (more than 1 page of results) the search breaks for next items as it scans only the last pages of results. For example if first item - A has 2 pages, second item - B has 1 page, third item - C has 2 pages it will display full results for item A, no results for item B and only 2nd page of results for item C. As you can see here: http://i.imgur.com/iUxqRoX.png (captured during the scan) it also displays: "Scanning 2/3 (Page 2/1): - in this case it's Grave Moss that only has 1 page of auctions, so scanning 2nd page of auctions returns no results.

Cheers,
Matt

**Comment by shirsig** [comment]
Thanks for the detailed report, should be fixed.

**Comment by mateszbukaty** [comment]
Awesome!
