### ISSUE TITLE
[lua error]

### ISSUE THREAD

**Issue by Altoholic** [shirsig/aux-addon#300]
4x aux-addon\tabs\post\core.lua:341: attempt to perform arithmetic on field 'unit_vendor_price' (a nil value)
aux-addon\tabs\post\core.lua:341: in function `update_item_configuration'
aux-addon\tabs\post\core.lua:563: in function <aux-addon\tabs\post\core.lua:559>

Locals:
deposit_factor = 0.050000
duration_factor = 12
stack_size = 1
stack_count = 2
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'unit_vendor_price' (a nil value)"
aux = <table> {
}
info = <table> {
}
money = <table> {
}

**Comment by shirsig** [comment]
Did this appear with the recent update? Any info on how to reproduce? It kind of looks like an old bug that caused corrupted post tab settings. The bug was fixed but corrupted settings might still be there for specific items.

**Comment by Altoholic** [comment]
Not sure how to accurately reproduce it.
Right now i get it again, it was while posting iron buckles.
And they were posted, but i had to close the AH and open it again to see them.

**Comment by Altoholic** [comment]
And again with frost oils.
I had 6 in my bags, posting 2 stacks of 1.

**Comment by shirsig** [comment]
can you try **/aux clear post** to see if the issue reappears afterwards?

**Comment by Altoholic** [comment]
I did after you posted your message (2 days ago), and i just got the bug again.
With frost oils, again.
Again with 6 in my bags, posting 2 stacks of 1.

**Comment by shirsig** [comment]
Strange, I still haven't ever had it happen.

**Comment by Altoholic** [comment]
I got it again, posting dark iron bars. I posted multiple stack size with no problem, and then with one stack of 8, i got the bug.

I have the feeling it can happen when the addon have to make a posting pile from a certain size coming from at least 2 different piles, because nothing of the desired size exist in the bag.

Should i continue to update that bug with the errors i get (it's always the same error, but the items vary) ?

**Comment by shirsig** [comment]
Yes, please. It's strange because there was a bug with posting a remainder stack with the previous version, though more severe and 100% reproducible, but now I have no issues with it.

If anyone else is reading this and has the same issue please comment as well.

**Comment by Altoholic** [comment]
Same error, posting 1 mithril casing (11 in my bag).

**Comment by Altoholic** [comment]
Same error, posting 1 stack of 8 dark iron bars (22 in my bags).

**Comment by Altoholic** [comment]
Same error, with Skullsplitter Coin, posting a stack of 15 (260 in my bag).

Again, as they stack by 250, aux had to grab from 2 different piles, which very likely seem to be part of the problem.

**Comment by Altoholic** [comment]
Same error, with Hakkari Coin, posting a stack of 15 (265 in my bag).

So, that invalidate my previous theory, because there was no reason to grab from 2 different piles there.

**Comment by shirsig** [comment]
Could you try manually deleting the addon and redownloading? And perhaps also the savedvariables. It's really strange that this happens to you so frequently and not once to me.
Also, in classic, unlike vanilla, assembling the right stack sizes and posting multiple stacks is actually done with an api function.

**Comment by Altoholic** [comment]
OMG, i did it without thinking... and i lost all my saved searches. Hundred of them T_T
And all my other settings (including the "hidden" one i can't find back, to see/set the starting price below competition).
You really need to make an export settings thing.

No more errors since the deletion of saved variables... so far (i have not go under all my usual buy and sale, for obvious reasons).

**Comment by shirsig** [comment]
Damn, sorry :( The setting you're looking for is /aux post bid

**Comment by Altoholic** [comment]
After a fresh install of Aux: same error, posting 1 mithril casing (11 in my bag).

**Comment by Altoholic** [comment]
Same error, posting 1 stack of 8 dark iron bars (26 in my bags).

**Comment by shirsig** [comment]
Did you try disabling other addons?

**Comment by Altoholic** [comment]
I kinda gave up on that one : even if it's a very common error, i just have to select another item, and the problem is gone (until the next time ^^). A bit annoying, but not game breaking.
But today i got errors with dark iron bars, only when i post a stack of 8. I tried a lot of other kind of stacks of dark iron bars, but it's only the stacks of 8 that make the bug appear. It can still be (un)luck, tho.

**Comment by shirsig** [comment]
Did you ever try disabling other addons? I use it daily and still have never had this error.

**Comment by Altoholic** [comment]
No. I'm using around 50 addons, and finding the one (if any) causing the conflict will take forever. As it's a minor problem, i'll just live with it.

But i'll try again with only Aux next time i'm selling dark iron bars. As the stack of 8 causing the bug seem 100% reliable, these days.

**Comment by Altoholic** [comment]
And so, after some other inconclusive tests (no 100% reproducible, even if sometimes very close), i read "Updated how the Auction House is scanned. It will only scan now when a user places an item up for sale or they are viewing their auctioned item list.
Added protections to the Auction House scanning to prevent it from interfering with any other addons or regular Auction House actions. This means that auction scans will only occur if C_AuctionHouse.IsThrottledMessageSystemReady() returns true and the server is ready for a query." from the BagSync changelog addon, and since that update, the error is gone.

So, i guess it was a conflict, after all, and i have an addon using the AH beside Aux, which i did not know.
