### ISSUE TITLE
[lua error]

### ISSUE THREAD

**Issue by Altoholic** [shirsig/aux-addon#303]
That one is constantly spamming, 
It appeared after i installed https://www.curseforge.com/wow/addons/instance-tracker , so maybe that's related?

280x aux-addon\tabs\post\core.lua:352: attempt to perform arithmetic on field 'unit_vendor_price' (a nil value)
aux-addon\tabs\post\core.lua:352: in function `deposit_amount'
aux-addon\tabs\post\core.lua:340: in function `update_item_configuration'
aux-addon\tabs\post\core.lua:554: in function <aux-addon\tabs\post\core.lua:550>

Locals:
deposit_factor = 0.050000
duration_factor = 12
stack_size = 8
stack_count = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'unit_vendor_price' (a nil value)"
info = <table> {
}

**Comment by Altoholic** [comment]
And it's gone now, after i closed and then re open the AH.
Oh well.

**Comment by shirsig** [comment]
Hm, I did make a change there in an update from yesterday to prevent posting when the user can't afford the deposit (would fail anyway of course but it was bugging aux until UI reload)

I haven't been able to get any error with my testing, though. Do you know what steps you took before it happened?

**Comment by shirsig** [comment]
I fixed an issue which I suspect caused this. I think it had to do with some special items that can't be auctioned like armor with reduced durability or items with used charges.
