### ISSUE TITLE
Suggestion: set bid and buyout price at the same time when posting

### ISSUE THREAD

**Issue by wodim** [shirsig/aux-addon#304]
When I post auctions I always set the bid and buyout price to the same amount because I don't want people bidding on my items. I wish there was a way to do this automatically so I don't have to type the same amount twice for every auction I post.

My suggestion is: if you empty the bid price input field, when that input field loses focus, copy the contents from the buyout price.

**Comment by Altoholic** [comment]
By default, this is exactly what Aux does.
To have a bid different from the buyout, you have to activate some parameter.

**Comment by shirsig** [comment]
In the tbc beta version I've added a feature where you can right click on the bid input to make it the same as the buyout value and vice versa.
