### ISSUE TITLE
Starting bid price is calculated wrong

### ISSUE THREAD

**Issue by 213983770** [shirsig/aux-addon#307]
When `/aux post bid` is set on and you select a price on the bid tab, the starting bid is calculated wrong. The unit bid price is incorrectly divided by the stack size. 

Unit bid price should be 18g 55s, not 6g 18s 33c:
![image](https://user-images.githubusercontent.com/53582105/102026821-c68f1d00-3da8-11eb-8b84-8bd831c5d989.png)

**Comment by shirsig** [comment]
It's not a bug, this is for undercutting the stack prices of auctions, not the unit prices, in order to appear higher up in the default ah sorting which can only sort by stack bid price.

**Comment by 213983770** [comment]
Ok, my assumption for this feature is that I would be able to undercut both buyout and bid price at the same time so that my auction will be the highest in default sort.  But don't understand how bid and buyout price can be completely different when the difference between lowest bid and buyout is couple of silver.

So if I post with these settings the buyout price then ends up being double of the currently listed lowest buyout (1g 24s 3c, the 2 top auctions are mine):
![image](https://user-images.githubusercontent.com/53582105/102027042-57b2c380-3daa-11eb-862d-b8e6e5339286.png)

So selecting the lowest price on both panels with a stack of 2 will post an auction where the buyout price is 2x of the current lowest listed buyout price.

**Comment by shirsig** [comment]
You're posting a stack of 2. The lowest has a stack price of 63, so to undercut the stack price you need a unit price of less than half of that.
