### ISSUE TITLE
Not able to Search for Arcane Dust

### ISSUE THREAD

**Issue by Lipovske** [shirsig/aux-addon#318]
When searching the action house for "Arcane Dust" this is what shows up:
![Aux Bug](https://user-images.githubusercontent.com/983934/120926126-9b2b2200-c6a9-11eb-8143-4a5473674652.PNG)
This is what shows up when just searching for "Dust"
![Aux Bug2](https://user-images.githubusercontent.com/983934/120926037-3374d700-c6a9-11eb-9122-a2c82ebe09e2.PNG)

Thanks for the addon

**Comment by Lipovske** [comment]
Also having issues where action loading will stop working after the latest update. reload fixes this

**Comment by shirsig** [comment]
/aux clear item cache
and 
/run ReloadUI()
will fix those issues

**Comment by Lipovske** [comment]
Thanks clearing item cache worked to fix auto complete and arcane dust issues.

/reload certainly works to fix the auction loading issues, but having to /reload everytime it happens is not really a fix.

**Comment by shirsig** [comment]
reloading was to make the clear cache stick in case you don't exit the client properly afterwards
For the other problem please open a separate issue.
