### ISSUE TITLE
Lua error while calling slashcmd

### ISSUE THREAD

**Issue by MickeyPickey** [shirsig/aux-addon#320]
`1x aux-addon\color-Color.lua:8: attempt to concatenate local 'text' (a boolean value)
[string "@aux-addon\color-Color.lua"]:8: in function `blue'
[string "@aux-addon\core\slash.lua"]:71: in function `?'
[string "@FrameXML\ChatFrame.lua"]:4825: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4488: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4524: in function <FrameXML\ChatFrame.lua:4520>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = <table> {
}
text = true
r = 41
g = 146
b = 255
a = 1
(*temporary) = "|c012992FF"
(*temporary) = true
(*temporary) = "|r"
(*temporary) = 41
(*temporary) = 146
(*temporary) = 255
(*temporary) = "attempt to concatenate local 'text' (a boolean value)"
mt = <table> {
 __concat = <function> defined @aux-addon\color.lua:13
 color = <table> {
 }
 __metatable = false
 __newindex = <function> defined @aux-addon\libs\package.lua:18
 __call = <function> defined @aux-addon\color.lua:5
}
`

**Comment by sipertruk** [comment]
in core/slash.lua replace

> aux.print('- post bid [' .. aux.color.blue(aux.account_data.post_bid or 'off') .. ']')

by

> aux.print('- post bid [' .. status(aux.account_data.post_bid) .. ']')

**Comment by shirsig** [comment]
You have corrupted user preferences.
Running one of
/aux post bid unit
/aux post bid stack
/aux post bid off
should fix it.
