### ISSUE TITLE
Setting post duration not working

### ISSUE THREAD

**Issue by jjyoung1** [shirsig/aux-addon#321]
Version 2.5.1

When trying to set the post duration using
_"/aux post duration 8" or "/aux post duration 8h"_
it only shows the list of settings as if you just type
_"/aux"_

**Comment by shirsig** [comment]
In TBC you can only set it to one of 12, 24, 48.

**Comment by jjyoung1** [comment]
I had tried doing 12 and 12h also, which didn't work.  I tried it again this morning and it started working...go figure
