### ISSUE TITLE
/aux post bid ON   - doesnt work for classic era

### ISSUE THREAD

**Issue by vicand98** [shirsig/aux-addon#336]
/aux post bid ON   - doesnt work for classic era

**Comment by shirsig** [comment]
it's **/aux post bid unit** or **/aux post bid stack**

**Comment by vicand98** [comment]
what i mean is that you cant see the starting price for an item when you try to post it on ah. Was trying to turn it on with /aux post bid on/unit/stack none of those seem to affect aux in order to allow you to see the starting price for the item in the posting tab. The runecloth imagine is what would like it to be meanwhile the imagine with the ore is what currently is.

![image](https://user-images.githubusercontent.com/95031952/143602519-41ab30c4-3e1f-44d3-8cce-200376fb32e7.png)
![image](https://user-images.githubusercontent.com/95031952/143602810-968d341e-ef28-4ac0-874b-e580fa6f1a92.png)
![image](https://user-images.githubusercontent.com/95031952/143602934-e30d058b-4105-49ad-8a37-678b4db0b33f.png)

**Comment by vicand98** [comment]
here is a yt video starting at 11:30 with what i meant about /aux post bid 

 https://youtu.be/VyobxKoTBnE?t=690

**Comment by vicand98** [comment]
it worked after a few tries even tho at first it didnt wanted to do its job. Thank you for your time! have a nice week :D
