### ISSUE TITLE
Aux bug

### ISSUE THREAD

**Issue by broskbenny** [shirsig/aux-addon#34]
Hello. I get the following bug when I do a fresh install of the addon.

![image](https://cloud.githubusercontent.com/assets/20017815/16173185/dd33457a-3599-11e6-99a0-1e79586ef02e.png)

Is there any solution to this? Many thanx.

**Comment by shirsig** [comment]
I assume you upgraded from an older version? try deleting the aux savedvariable files in your WTF folder.
