### ISSUE TITLE
WowUP support

### ISSUE THREAD

**Issue by lgrano** [shirsig/aux-addon#343]
Overwolf has disabled the curseforge API, now addon managers like nexus, minion or WowUP wont be able to download from curse anymore. Personally i would like to avoid installing anything by overwolf on my computer.
When trying to install via github url, wowup says it require a zip release with a -bc or -bcc suffix for burning crusade, would you consider github releases for wowup?
Wowup also supports [Wowuphub](https://wowup.io/guide/wowup/hub), Wowinterface or Wago as alternative.

**Comment by lauenchr** [comment]
https://github.com/shirsig/aux-addon/pull/342

This PR I created a while back would resolve this, no feedback on it so far, unfortunately.

**Comment by Cephel** [comment]
https://github.com/Cephel/aux-addon

I created a fork that includes a release of the latest version, feel free to use that in the meantime. It works directly via WoWUP's GitHub import (install via URL feature).

**Comment by shirsig** [comment]
@mooreatv yes, that's ok with me.

**Comment by KevinTyrrell** [comment]
> instead of forking - this repo works fine (thanks @shirsig ) but to add it to wowup's hub so it works without manual addition, the author needs to agree to it (either in discord or probably if you state it's ok here that should work)

Confirmed that the repo is now compatible with WoWUp.

This issue may be closed.

**Comment by mooreatv** [comment]
@shirsig can you tag the latest/make a github release so wowup isn't stuck on the june version?

looks like you need to just tweak the github action as it fails right now:
https://github.com/shirsig/aux-addon/actions/runs/3089254139/jobs/4996660081

aux-addon.toc has an interface version that is not compatible with the game version "bcc" or was not found.

thanks in advance!
(that would unstuck https://wowup.io/addons/2436061 )

**Comment by shirsig** [comment]
@mooreatv I think it's fixed now.
