### ISSUE TITLE
[Feature Request] Add filter for inscription pigments or allow multi item search

### ISSUE THREAD

**Issue by mtoedtem** [shirsig/aux-addon#344]
This might be just me not understanding how to craft a filter for multiple items but with inscription coming out could we get a filter for say [Alabaster Pigment](https://www.wowhead.com/wotlk/item=39151) that would return the following herbs:

Earthroot, Peacebloom, Silverleaf

I've tried to craft a search for those 3 herbs but haven't gotten it working.

**Comment by shirsig** [comment]
You can chain multiple queries with semicolons like this: **earthroot/exact;peacebloom/exact;silverleaf/exact**
