### ISSUE TITLE
Value tooltip isnt update after Scan

### ISSUE THREAD

**Issue by ProzacRogue** [shirsig/aux-addon#347]
Hi, the value tooltip its always the first scan you did, when i re-scan the auction after the first time the tooltip never update itself, my workaround to update the prices its to delete aux files in WTF folder

**Comment by shirsig** [comment]
It may take a few days of scanning for the price to update. The price is a historical value meant to help you see if the current auctions are overpriced/underpriced so updating it immediately would make no sense.

**Comment by ProzacRogue** [comment]
then the tooltip value its pointless, bad addon

**Comment by shirsig** [comment]
I just said what it's for. If you wanna buy something and it's overpriced on that day for example you know you better wait until it's back to its regular price which is what the tooltip shows and what the percentages are based on. There's also **/aux tooltip daily** which you can use to show the lowest price scanned on that day.
