### ISSUE TITLE
[WOTLK] Posting item yields no results on first page and does not suggest price

### ISSUE THREAD

**Issue by Valdiralita** [shirsig/aux-addon#349]
When you try to post an item aux searches for the item to show prices. It searches only on the first page, if no items are there then it wont show any prices. However if there are items but not the exact ones it wont search on page 2.
I suggest changing it to an exact search.

Example: 

1. Try to post Borean Leather.
2. No prices shown for items in auctionhouse.
3. Search for Borean Leather/exact, items with prices are shown.
4. Search for Borean Leather. The search will find "Borean Leather Scraps".

I assume Posting an item searches for "Borean Leather" , first page results are only "Borean Leather Scraps". Aux assumes no "Borean Leather" in auction house and doesnt continue searching for prices:

![grafik](https://user-images.githubusercontent.com/1066165/197016107-1546ef8e-54aa-4c47-babe-879e2349d01c.png)

**Comment by shirsig** [comment]
I actually implemented it so that it would keep scanning subsequent pages until it finds at least one auction, but I don't think I ever tested it. Will have a look soon.

**Comment by shirsig** [comment]
This should be fixed now.
