### ISSUE TITLE
Stack size / Stack count

### ISSUE THREAD

**Issue by yutsuku** [shirsig/Aux-AddOn#35]
![wowscrnshot_072916_155258](https://cloud.githubusercontent.com/assets/1192561/17250835/708af8fa-55a6-11e6-9a5b-2794664548c1.png)

Since the update with hamburger menu (or somewhere around there, not exactly sure) I cannot see both stack size & count. Tried deleting Aux data from both account and character folder in WTF with no avail. 

Any idea what's going on?

**Comment by shirsig** [comment]
Hm, I changed the font size I think from 16 to 15. Have had strange issues with that before, people seeing the 3 dots for certain font sizes.  Where did you get your client? Have you downloaded it recently?

**Comment by shirsig** [comment]
Nevermind, I'm getting the same issue in fullscreen mode. In windowed it's working fine though, trying to find out why

**Comment by shirsig** [comment]
Ok, should be fixed, thanks for reporting.
