### ISSUE TITLE
Error with consumable items with stacks (e.g. drums)

### ISSUE THREAD

**Issue by tilliwilli** [shirsig/aux-addon#351]
Context: WotLK Classic

Use case:
- I have some partly used Drums of Forgotten Kings (https://www.wowhead.com/wotlk/item=49633/drums-of-forgotten-kings) in my inventory as well as some unused ones with the full 50 charges
- I want to post the unused ones in the AH

This shows a WoW error message as soon as I click the item, since it's not allowed to post items with used charges. Aux itself does not recognise this error at all and wants to place all of them, which apparently also fails without aux realizing. It did not post any of them, maybe because the used ones were the "first" it found in my inventory and tried to post (?)

I could not find a way to make this work with aux (apart from the obvious "put the used one in the bank temporarily"), so I needed to resort to the Blizzard UI to only post the stacks that are postable manually.

Solution: Aux should realize consumable items with used charges and completely ignore them for posting if mixed with the same items with full charges.

**Comment by shirsig** [comment]
All charge ittems need to be hardcoded because I couldn't find another way to determine the max charges. This one I guess I missed. Will check on the weekend and add missing ones.

**Comment by shirsig** [comment]
Should have been fixed a while ago.
