### ISSUE TITLE
Error when searching

### ISSUE THREAD

**Issue by xC0DEB10C** [shirsig/aux-addon#36]
After downloading the current version I get errors now every time I search for something. I've cleared my WTF but it still happens.

Interface\AddOns\Aux-AddOn\core.lua:93:
    attempt to call field `?' (a boolean value)

Interface\AddOns\Aux-AddOn\control.lua:36:
    attempt to call local `k' (a nil value)

the last one will repeat and you can't close it until the window closes.

**Comment by shirsig** [comment]
Hey, sure you have the very newest versions? Did multiple updates yesterday (the version number may not always have been updated)

**Comment by xC0DEB10C** [comment]
yeah, downloaded master through the git website here.

**Comment by shirsig** [comment]
Ah, found the problem. It only happened when you didn't have an auto buyout filter set, that's why it was working for me. Anyway, should be fixed now, thanks.
