### ISSUE TITLE
Wrong order in search results

### ISSUE THREAD

**Issue by skmd0** [shirsig/aux-addon#364]
It seems like there is a bug with sort order of search results. In the picture below you can see that the highest priced item is being displayed first and it's `% Hist. Value` seems to be lowest.

![image](https://github.com/shirsig/aux-addon/assets/52122032/d27b0862-9896-4cdb-a027-ed746773cf93)

**Comment by shirsig** [comment]
Presumably they are different items (different stats) with the same name.
