### ISSUE TITLE
Sometimes hangs on a getall scan

### ISSUE THREAD

**Issue by tjesp** [shirsig/aux-addon#375]
When I scan the auction house sometimes it takes forever. Like half an hour before I quit the scan.

I think the issue is that you disconnected from the auctioneer due to phasing. TSM and others have the same issue. I know that TSM writes a message if you disconnected due to phasing.

I wonder if you could do anything about it like ending the scan premature.

**Comment by shirsig** [comment]
Note that Aux does all processing immediately as the data comes in - nothing is delayed until the end of the scan - so if the scan gets stuck when the progress bar is near the end it doesn't matter much, and if you see that the progress bar stops moving it should be safe to assume that it's stuck and you can terminate it yourself. Also, Aux aggregates scan data into a single data point per day with minimum prices for each item on that day, so rescanning multiple times (e.g., in case the scan was interrupted early) also does not falsify the historical data.

**Comment by tjesp** [comment]
Alright, so I assume everything is ok
