### ISSUE TITLE
Question about time left filter

### ISSUE THREAD

**Issue by tjesp** [shirsig/aux-addon#376]
The "left" filter for time left. If I set it to "2h" does it take all less into consideration like "30m" left?

**Comment by shirsig** [comment]
No, only what the blizzard API considers as 2h (which I guess effectively may be anything between 2h and 30m, 30m excluded). If you want to include 30m you have to explicitly add both: **or2/left/2h/left/30m**

**Comment by tjesp** [comment]
Ok perhaps I do not understand the notation. Is this correct:

bid-percent/20/or2/left/2h/left/30m

If I want to search for bids below 20% market with 2h left or less?

**Comment by shirsig** [comment]
Yes, correct.
