### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by ShaunDreclin** [shirsig/aux-addon#39]
Is there any way to put the aux features into the vanilla auction interface like auctionator on retail does it? I'm really not a fan of the flat grey boxes.

**Comment by shirsig** [comment]
no.

**Comment by ShaunDreclin** [comment]
Could a new GUI be created then? It really is an eyesore with the rest of the vanilla interface haha

**Comment by shirsig** [comment]
sorry, I'm finally happy with the current one after having gone through like 3 complete rehauls and it's a lot of frustrating, boring work to create GUIs
