### ISSUE TITLE
Aux folder name issue on windows 10

### ISSUE THREAD

**Issue by oppahansi** [shirsig/aux-addon#40]
AUX is a system reserved type / name and therefore invalid.
https://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/

Creating new Folder or copying Aux into interface Addon folder is not working anymore.

**Comment by shirsig** [comment]
actually, aux's .toc/folder name has always been "aux-addon" rather than just "aux" for that reason.
