### ISSUE TITLE
Didnt scan some items in Consumable

### ISSUE THREAD

**Issue by Gamelander** [shirsig/aux-addon#41]
Didnt scan some items in Consumable. It doing in Post tab, for example Raw Redgill, Raw Nightfin Snapper

**Comment by shirsig** [comment]
Are you sure it's not just collapsed? The auction listings (except for the one in the post tab) show only one entry per item per default. If there are more the count is colored in blue and you can double click to expand.

**Comment by Gamelander** [comment]
![screen shot 09-07-16 at 09 51 am](https://cloud.githubusercontent.com/assets/22045958/18302465/ca39d408-74e0-11e6-9277-768d5ac0b6e4.JPG)
Empty fields like that item is not presents in AH.  But with ordinary scan in standart 
interface those items present in AH
![screen shot 09-07-16 at 09 55 am](https://cloud.githubusercontent.com/assets/22045958/18302554/3139891e-74e1-11e6-872b-95c520f94786.JPG)

**Comment by shirsig** [comment]
hm, I can't seem to reproduce it. redgills work fine and there are no nightfin snappers on the ah right now.

**Comment by Gamelander** [comment]
Reproduce it 1 min ago without any other addons after deleting WTF folder. In POST tab didn't scan no one item that name beginning with "Raw" (Raw nightfin snapper, Raw Summer Bass, Any other items work fine.

**Comment by shirsig** [comment]
Strange, just tried 5 different raw fish and they all worked fine. What server are you playing on? Not kronos?

**Comment by Gamelander** [comment]
Kronos II

**Comment by shirsig** [comment]
hm, i'm on k1 right now, let me log over quick

**Comment by shirsig** [comment]
no problem on k2 either: [](http://i.imgur.com/d8Av6RI.png)

**Comment by Gamelander** [comment]
Sorry than. Dont know how i have that errors. Thank you very much

**Comment by Gamelander** [comment]
Thank you very mush! Working fine after deleting WDB !

**Comment by shirsig** [comment]
great, glad I could help :)
