### ISSUE TITLE
scan error

### ISSUE THREAD

**Issue by cnolimes** [shirsig/aux-addon#45]
Getting this error anytime I'm trying to scan the whole AH. The error usually shows on a certain page of the scan. https://imgur.com/a/jpb0E

**Comment by shirsig** [comment]
Seems like you have partial historical data from a very old version which is not compatible with the current format.

**Comment by cnolimes** [comment]
aww, I'll try to delete the data ;(

**Comment by shirsig** [comment]
you might be able to keep it if you can identify the offending record

**Comment by shirsig** [comment]
The last element of a history record is the list of historical values. they are separated by semicolons and the values are pairs of time and price separated by @. example: 3281@1474322400;3105@1474236000.
It seems you have an entry in a list of some record which is missing the time

**Comment by cnolimes** [comment]
Tried to find out the item causing the problem but it was too tricky so I deleted the whole database, everything works fine now. Thank you for the support <3
