### ISSUE TITLE
fubar_bug

### ISSUE THREAD

**Issue by 0ldi** [shirsig/aux-addon#46]
Hi, getting fubar's view (bottom) when i use last aux version
http://imagehost.spark-media.ru/i4/B41A2236-C435-6FA0-C162-97D27CFA27D6.png
but if i turn off it, everything comes back to normal (top).
No idea how fix this, can't found any connection with fubar...
My old (about year ago) version work fine and no destroy fubar
p.s. in broken state fu_addons not only the disabled but also gone from there

**Comment by shirsig** [comment]
My best guess is that some variable is global which shouldn't be and interferes with it. The only way to find out is if you give me a link to the fubar version you're using and ideally the line where the error happened.

**Comment by xak1989** [comment]
Errors:
`[2016/10/08 17:19:49-3368]: FuBar\FuBar.lua:649: cannot change a protected metatable
<in C code>: in function `setmetatable'
FuBar\FuBar.lua:649: in function <Interface\AddOns\FuBar\FuBar.lua:646>
FuBar\FuBar.lua:917: in function `LoadPlugin'
FuBar\FuBar.lua:1036: in function `event'
AceEvent-2.0\AceEvent-2.0.lua:430: in function <...e\AddOns\!RealLag\Libs\AceEvent-2.0\AceEvent-2.0.lua:407>

  ---`

`[2016/10/08 17:19:44-3368]: core\cache.lua:184: bad argument #1 to `tinsert' (table expected, got nil)
<in C code>: in function `tinsert'
core\cache.lua:184: in function `scan_wdb'
core\cache.lua:27: in function `f'
aux-addon\aux-addon.lua:43: in function <Interface\AddOns\aux-addon\aux-addon.lua:39>

  ---`
(i tried turn off RealLag, no effect)

Unfortunately I do not remember where I was taking my version fubar, but it seems to be a normal site, like wowace.com. Uploaded here: https://dl.dropboxusercontent.com/u/13666543/FuBar.zip

**Comment by shirsig** [comment]
ah I see. it tries to set a metatable on the global environment which causes a conflict with my module system. kind of a crazy thing to do. I only did it for syntactic sugar so I could remove it, and I guess I will, but changing the module system will require quite a lot of other changes so it might not happen very soon.

**Comment by xak1989** [comment]
ok thx, waiting if this is a long-term problem. Do you recommend to stay on my old working version, or there is something pre-conflict version that would work with fubar?

**Comment by shirsig** [comment]
if you checkout something from around june I think that should be fine.

**Comment by shirsig** [comment]
The issue should be fixed already now.

**Comment by xak1989** [comment]
Wonderful! at first sight everything seems to be working, thanks

**Comment by 0ldi** [comment]
This is not a problem of the past, I just did not want to create a new issue because of a small problem.

Felcloth can be bought in Winterspring, but it is not shown in the Aux ( "/aux tooltip vendor buy" enabled).

I also have a question about a complex combination with other addons.
For a long time I had a "full auctioneer pack", some of which did not work without the main "Auctioneer", and I also remember that there are other addons, do not work without BeanCounter and Stubby.
So if I use the Aux, can I completely delete "Auctioneer" or should I just turn it off or kept switched on. And what of the "full auctioneer pack" I just can disable \ deleted but keep the full functionality including other addons?

**Comment by shirsig** [comment]
aux is completely standalone, no other addons required
as for the felcloth, this is not an aux issue. aux gathers vendor prices as you visit vendors. if you haven't been there it won't know about it. if you've imported the data from some other addon (e.g., informant) then that's a problem of that addon's data.

**Comment by shirsig** [comment]
btw, what do you think of the current version of aurae (former ccwatch)? I think the DR bars are kinda ugly, open for suggestions for a better label.

**Comment by 0ldi** [comment]
I'll check aurae a little later, after I finish filtering "auctioneer pack". 
But the problem is that I do not fully understand all the relationships between the "Auctioneer", "BeanCounter", "Stubby", "EnhTooltip", "Informant", "Enchantrix".
Something of this is used in the addon EnchantingDB, there are other dependencies. And all this is compounded, because I have 228 addons right now :D
