### ISSUE TITLE
conflict with your cooldowns addon

### ISSUE THREAD

**Issue by TheRealYasri** [shirsig/aux-addon#47]
I am using the lastest version of your aux and cooldowns addons as of the time writing this. A error box with no text and a okay button appears when i log in with this two addons enabled.

I disabled all my addons and tried them both separately and they do not show the error but when both on together they do.

If i can some how give you more info just ask.

![aux error](https://cloud.githubusercontent.com/assets/20503367/20660286/6b53ae32-b50e-11e6-882e-bee88578c4c8.png)

**Comment by shirsig** [comment]
seems one of my other addons was suppressing this. should be fixed now. you'll have to update both aux and cooldowns.
