### ISSUE TITLE
[Request] Add whisper feature

### ISSUE THREAD

**Issue by jclock** [shirsig/aux-addon#48]
Hello, great work with the addon! I wondered if it was possible to have an option with the following scenario involving two separate characters, A and B:

A (out and about the world)
B (guy who sits at the AH nonstop)

A whispers B: price check [Poniard]
B whispers A: AH 0c | Vendor 7s30c | DE value 0c

Or something thereabouts, maybe with a white/black list of names to or not to respond to.

**Comment by shirsig** [comment]
Hey. I'm not really interested in adding features for playing with multiple accounts, sorry. Nost was banning for that and I assume the new nost/elysium will also, and while it was technically allowed on retail by paying for multiple accounts it's clearly not the intended way to play, as evidenced by many things, like restrictions for factions for characters on the same account, savedvariables of addons not being sharable between multiple accounts etc.
