### ISSUE TITLE
Filter Export error

### ISSUE THREAD

**Issue by Monteo** [shirsig/aux-addon#51]
![wowscrnshot_122616_011227](https://cloud.githubusercontent.com/assets/24656088/21472371/ed23ee80-cb08-11e6-86d3-c96a9363eddd.jpg)

**Comment by shirsig** [comment]
that's with the newest version? for me that line is ```return (slot_index or 0) > 0 and slot_index or nil``` and it seems impossible to get that error

**Comment by shirsig** [comment]
working now?

**Comment by Monteo** [comment]
yep
