### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by jringo12** [shirsig/aux-addon#54]
I scale my UI and when I do that the buttons just turn to ...
I do not know the addon well enough to not see the words. I haven't been able to find a way to resize it or the text.

**Comment by bitingsock** [comment]
I too have this problem. I can't stand full scale ui.
![asd](https://cloud.githubusercontent.com/assets/6302101/21792433/9a94b4e6-d69e-11e6-8882-30d8dc3ae79d.jpg)

**Comment by shirsig** [comment]
You don't have a custom font? resizing alone doesn't cause this for me.

**Comment by bitingsock** [comment]
In the mean time I am reducing the values of M.font_size in 
"~\Interface\AddOns\aux-addon\gui\core.lua"

**Comment by bitingsock** [comment]
No custom fonts.

**Comment by shirsig** [comment]
what resolution?

**Comment by bitingsock** [comment]
1920x1080
I have just discovered something interesting,
@jringo12 is your resolution the same and scale set exactly to this value?
![asd](https://cloud.githubusercontent.com/assets/6302101/21792631/01426ade-d6a0-11e6-9f98-3b71a4a518a4.jpg)
Setting it to any other scale seems to alleviate the problem.

**Comment by bitingsock** [comment]
I looked at my wow config and the value is uiScale "0.75"
Something special about this number?

**Comment by shirsig** [comment]
no. I may have fixed it. can you try with the newest version?

**Comment by bitingsock** [comment]
that fixes it. Any idea why it only becomes a problem at uiScale "0.75"?

**Comment by shirsig** [comment]
You mean it still doesn't work with 0.75?

**Comment by bitingsock** [comment]
Ah, sorry. It works at .75
I was just curious
