### ISSUE TITLE
tooltip quest? 

### ISSUE THREAD

**Issue by Monteo** [shirsig/aux-addon#57]
![wowscrnshot_010917_131352](https://cloud.githubusercontent.com/assets/24656088/21763338/055049ee-d690-11e6-9a76-209971ce22b4.jpg)

**Comment by Monteo** [comment]
all quest with item reward

**Comment by shirsig** [comment]
Not for me. Tried disabling other addons?

**Comment by Monteo** [comment]
ok sorry
questie

**Comment by Monteo** [comment]
Dyaxler commented an hour ago
...for what it's worth I tried to look into this tonight. I looked at the code for 'aux-addon' and they aren't using a proper tool-tip hooking method. Without knowing exactly what issue it has with Questie I'd say that it's a mod incompatibility.
https://github.com/AeroScripts/QuestieDev/issues/334

**Comment by Monteo** [comment]
http://plays.tv/video/5874890880a7bcd55b/-wow-addon
My actions:
1 clear WDB
2 AUX + QUESTIE = error
3 - AUX = noerror, item cache
4 AUX+ QUESTIE = no error

**Comment by shirsig** [comment]
Not sure what could be wrong on my end. I'm using a vararg hook and passing everything along to the original function, which results in an error.

**Comment by Finrodi** [comment]
http://i.imgur.com/FPGuDQP.png

Same problem with a questitem. DOnt evne get a tooltip.

**Comment by shirsig** [comment]
https://github.com/AeroScripts/QuestieDev/issues/334#issuecomment-272708088
should be fixed now
