### ISSUE TITLE
confusion with multiple charge items

### ISSUE THREAD

**Issue by MrMarvin** [shirsig/aux-addon#58]
For example http://www.wowhead.com/item=20744/minor-wizard-oil which basically is ONE Item but hast FIVE charges is counted as ONE stack of FIVE items. This messes up posting as well as calculating for example vendor profit.

**Comment by shirsig** [comment]
This is intended. How does it mess up calculating vendor profit?

**Comment by MrMarvin** [comment]
> This is intended. How does it mess up calculating vendor profit?
In my case it was that the item was calculated to be sold to a vendor for 5 times 5s and therefore showing up as profitable when buying for like 20s. From looking into the price source .lua it seems that when fixing the price to 1s, the per stack calculation is correct. Otherwise we should not multiple per 'stack size'.

**Comment by MrMarvin** [comment]
I see you fixed the price source in the other project. Thanks a lot! Closing here.
