### ISSUE TITLE
Hook issue

### ISSUE THREAD

**Issue by sipertruk** [shirsig/aux-addon#60]
You're doing tooltip:Show() on frames you didn't create (tooltip.lua line 117).
It is the role of the creator to do that.
This is causing duplicate processing issues when an addon hooks the show function (Questie).

**Comment by shirsig** [comment]
Eh what? Those tooltips are blizzard frames. It's not their role to do anything anymore. The issue with questie was fixed here probably: https://github.com/AeroScripts/QuestieDev/issues/334#event-923579567

**Comment by sipertruk** [comment]
If I remove that line aux is working exactly the same, or please tell me what i am missing.

**Comment by shirsig** [comment]
Don't remember but I don't call functions for no reason. May have something to do with the money in vendor frames.

**Comment by sipertruk** [comment]
Useful only if you added a line in the tooltip in fact. Questie was bogus alright.

**Comment by shirsig** [comment]
Well, I am adding lines to the tooltip there no? Maybe it was about resizing the tooltip frame? I also vaguely remember something about wanting to move the icon-goldvalue when at a vendor below aux' added lines which required some weird code. Anyway, I hate superfluous code so if it's not obvious something is needed I probably tested to make sure it is.

**Comment by sipertruk** [comment]
Not always, it's not adding lines if options are disabled or for quest items unless for rare tradable ones.
I would check tooltip:NumLines() and tooltip:Show() only if needed, but it sure is your call.

**Comment by shirsig** [comment]
Oh, yeah, i guess. Actually there was no option to disable the historical value at first. Either way, I don't see the harm in always calling it. It's less code and no noticeable difference in performance.
