### ISSUE TITLE
Auto Buy

### ISSUE THREAD

**Issue by Yadba** [shirsig/aux-addon#61]
First off excellent addon, thanks a bunch.

sorry if I missed it somewhere, but I looked thru the readme and the old nost forum post and couldn't find any documentation on how auto-buy works other than how you toggle it in the saved searches menu.
(ie "Right-click on an entry will show a menu with various options, including toggling Auto Buy.")

what are the settings for autobuy? does it buy at a certain % of historical value? a certain price? or do i have to use some type of post filter and it will buy everything that makes it thru the filter?

Thanks,
Yadba

**Comment by shirsig** [comment]
It will buy anything that is encountered in a scan and matches the query for which auto buy is set, so yes, you need to use an appropriate post filter.
