### ISSUE TITLE
[Request] Automatically set price to the 100%-value

### ISSUE THREAD

**Issue by nukul4r** [shirsig/aux-addon#64]
Loving your addon, but for usuability I have a suggestion: Would it be possible to have an option to set the default price for an item to the 100%-value for bid and buyout when listing an item?

Thanks for your work!

**Comment by shirsig** [comment]
I think it's pretty useless as it's almost always better to undercut something.

**Comment by Kvel2D** [comment]
You can edit undercut formula directly in file tabs/post/core.lua in function undercut().  I know it's hacky but that's what I did.
