### ISSUE TITLE
[Reuqest] Switch for stack size and count

### ISSUE THREAD

**Issue by nukul4r** [shirsig/aux-addon#65]
When listing a stackable item, the default setting for stacksize is 1, with the stack count being the amount of items you have. Would it be possible to have a (global) option to switch this, so the default stack size is the amount of items you have (or the max stack size for that item type if you have more items than the max stack size)?

An example:
When I have 10 linen cloth, it will automatically set to 1 stack of 10 cloth. Later that day I come back with 7 cloth, it will set to 1 stack of 7 cloth. If I have 43 cloth, it will set to two stacks with 20 cloth. After I post the 2 stacks, it will set to 1 stack of 3 cloth.

I hope this explaination is understandable. Thanks for your awesome work!

**Comment by shirsig** [comment]
I'm not perfectly happy with how the post tab works but so far I haven't been able to come up with a better solution. The default is only 1 the first time you post an item and after that it remembers the last stack size you used. The problem with automatically setting the stack size is that it cannot be combined with saving the stack size (same problem for the price).

**Comment by shirsig** [comment]
Some post changes: https://forum.elysium-project.org/topic/23657-addon-aux-and-more/?page=10#comment-334410
