### ISSUE TITLE
Posting Auctions Stack Price

### ISSUE THREAD

**Issue by Spazzer13** [shirsig/aux-addon#66]
Hey,
I love this project/addOn. 

I've been wondering if there is anyway to put Stack price in the Post Page. I know you can sort by either Item or Stack price on Search Page and Auctions Page; however, Post page you can not and I find myself constantly putting items up for Stack Price instead of Item Price. This overshoots my intended prices for stacks.

Would love this added if there is no way to change this. 

![screen shot 2017-01-26 at 19 26 41](https://cloud.githubusercontent.com/assets/23638772/22356208/8a15f6d6-e3fd-11e6-802f-437ef36666f3.png)

**Comment by shirsig** [comment]
No. There are a few reasons. It wouldn't work well when changing the stack size, doesn't work well for comparing prices, there's the danger that you put too low a price rather than too high which is of course worse etc.

**Comment by Spazzer13** [comment]
I agree when comparing prices yes, what I am referencing is the option of posting a stack for a total price instead of per item.
