### ISSUE TITLE
[Reuqest] Advanced Trade Skill Window link

### ISSUE THREAD

**Issue by champi92** [shirsig/aux-addon#68]
Hello, do you think that data from aux can be implemented in the Advanced Trade Skill Window addon? I have found a similar implementation for Auctioneer:

https://github.com/Logonz/AuctioneerProffesion

**Comment by shirsig** [comment]
Sure, but not by me. (e.g. the hist value can be obtained with **require'aux.core.history'.value("itemid:suffixid")**
