### ISSUE TITLE
[Request] Number Of Times Item Has Been Seen On Tooltip

### ISSUE THREAD

**Issue by Patchett** [shirsig/aux-addon#69]
Hey Simon,
I am a long time user of Aux and really appreciate all of your work! I remember at one point you had a feature which showed the number of times you had seen an item in scans on the tooltip. I thought that this was very useful for gauging the integrity of price data, especially for rarer items. Are there any plans to add an option for this back in?

**Comment by shirsig** [comment]
No, it's not even possible to give an accurate number because auctions don't have a unique identifier, nor would it make sense with the current history which uses a median of daily minimum buyouts and it would give you a false security in many cases.
