### ISSUE TITLE
[Request] Charting

### ISSUE THREAD

**Issue by OverlyExcessive** [shirsig/aux-addon#71]
First of all, very nice add-on!

However one nice-to-have for us market mavens would be to have the add-on record historical prices and then of course support for some basic charts like linear and japanese candle sticks. Not sure if there is any open source LUA library that could be used for the charting I reckon it could be some work but for more deep analysis it would also be quite essential.

**Comment by shirsig** [comment]
Not likely to happen. To be able to collect enough data to make this interesting a different approach to scanning would be needed or else it would take up too much space. The big retail addons don't do this either and there is an addon specifically for this where you have to manually select a few items for which extensive history is kept: https://mods.curse.com/addons/wow/market-watcher. I think it's not something enough people would need to make it part of aux and also there are no such libraries for vanilla wow, not sure about retail, and in any case i think it would probably make more sense to just export the data to xml or csv or something and plot it in one of the countless sophisticated tools that already exist for this.
