### ISSUE TITLE
Colored already known recipes

### ISSUE THREAD

**Issue by Artur91425** [shirsig/aux-addon#72]
Add feature please highlight color already known recipes it makes addon FilterKnown. Or help to add the support for your addon. This is a very handy feature. With addon aux it does not work :(
https://github.com/ericraio/vanilla-wow-addons/tree/master/f/FilterKnown
![bandicam 2017-01-31 01-23-20-006](https://cloud.githubusercontent.com/assets/24303693/22444439/0212f360-e754-11e6-8e77-a91c62a6c405.jpg)

**Comment by shirsig** [comment]
why not just use the "usable" filter?
