### ISSUE TITLE
[Request/Question] Post Tab Changes

### ISSUE THREAD

**Issue by apskar** [shirsig/aux-addon#74]
Coming back to vanilla wow after a long time and using an older version of aux (~1 year old), I found out that it wasn't working properly for some reason (it wouldn't get the results for some items in the post tab), so I came here to get the latest version.

Among the changes I've noticed so far, the default duration for auctions is 8 instead of 24 hours and now I have to click on both the bid tab and the buyout tab to set the auction's price.

Are there any plans to add options for the two issues I mentioned above?
If not, I would like to request them and I would greatly appreciate them.

I assume that the solution to the first point would be a global setting that would set the default value of the duration of every auction.
In regards to the second one, I suppose that just setting the corresponding bid price to the buyout price clicked or vice versa would do the trick.

Thanks in advance for any feedback and thank you for the great addon!

**Comment by shirsig** [comment]
The bid listing is now optional (**/aux post bid** to activate it)
The default duration will not change because 8h is better most of the time (3x as high deposit with 24h)

**Comment by Jakobud** [comment]
> 8h is better most of the time (3x as high deposit with 24h)

Well.... 24 hours = 8 hours x 3 so it's actually the exact same rate. It's not like you are getting a better deal. You are only getting a better deal if your item WOULD HAVE sold in the first 8 hours. If you do 3 8hr auctions you are paying the exact same amount but have to deal with reposting which can be a huge pain with a bunch of stuff.

**Comment by shirsig** [comment]
Usually if it won't sell in 8 then it won't sell in 24 either. Especially now with regional servers with more defined peaks. But anyway, there is a setting for it: **/aux post duration 24**

**Comment by Jakobud** [comment]
Oh I had no clue that setting existed. Thanks!
