### ISSUE TITLE
[post-filters] Readme wording

### ISSUE THREAD

**Issue by theoden-dd** [shirsig/aux-addon#79]
> or/and2/profit/5g/percent/60/and3/bid-profit/5g/bid-percent/60/left/30m
This filter will search the whole auction house for auctions either with a buyout price of 5g or more higher than the market value and 60% or less of the market value or a bid price for which the same is true and in addition only 30m or less remaining.

This description is possibly wrong, since it states that price must be _at the same time_:

1. 5g or more **higher than the market value**
2. 60% or **less of the market value**

Also, please add a wording in formulae language, since it's not obvious which (in)equality sign is implied for a post filter.

E.g.:
```
(
  profit >= 5g
  and percent <= 60
) or (
  bid_profit >= 5g
  and bid_percent <= 60
  and time_left <= 30m
)
```
Which also shows that time condition is not applied for the buyout part.

The most brilliant solution would be a nice table for post filters with corresponding (in)equality signs. Or at least showing this implied signs in the filter builder.

Thanks for great addon and in advance!

**Comment by shirsig** [comment]
I actually used to have more detailed post filter names but chose to go for simplicity instead. The inequality implied is the only one that makes sense for the respective filter. There's no reason I can think of to make an upper bound for profit or lower bound for price or percentage. Time left only matches the one specified. I'll specify this in the readme when I have time, haven't updated it much in a while. Fixed the sentence you quoted.

**Comment by theoden-dd** [comment]
This holds while you only want to buy, but when one wants to sell, things go quite the opposite. This needs sell_profit (yeah, without upper bound, too), and >= for the percent filter. However, both are useless without the ultimate post filter "cheapest". It is implied to be "true" when used.

So, you're right: sane defaults are good. However they could be not obvious for a person who also wishes to sell.
