### ISSUE TITLE
A bug, a suggestion and a weird thing.

### ISSUE THREAD

**Issue by drtakhs** [shirsig/aux-addon#81]
Let me start by saying that i am an experienced AH player and i have been using AH addons to their limits for years. 

I feel the need to congratulate you for this addon, for a vanilla addon it's super good! 

Onto the point, i have been using aux for the past month and here is what i came across.

**The bug:**
There is a bug affecting all items with "x uses". I discovered it when auto-buy bought something that it shouldn't. Let me provide some screenshots.

![item price fault](https://cloud.githubusercontent.com/assets/15212862/22980405/05c56df8-f3a2-11e6-9b2a-694247c3c101.jpg)

![actual vs aux](https://cloud.githubusercontent.com/assets/15212862/22980411/0d5254be-f3a2-11e6-8df2-9f0158f3a2a9.jpg)

![tooltip charges items](https://cloud.githubusercontent.com/assets/15212862/22980416/113e9718-f3a2-11e6-9d6c-5bd62f7addbf.jpg)

![another example](https://cloud.githubusercontent.com/assets/15212862/22980425/17b43486-f3a2-11e6-9525-4703082af3d6.jpg)

![another item](https://cloud.githubusercontent.com/assets/15212862/22980440/1ec7b446-f3a2-11e6-8db9-428414ef8d82.jpg)

So i noticed this strange behaviour when auto-buy bought the [Discombulator Ray] item thinking that i would make a vendor profit! The addon calculated the vendor price to be 5x10s instead of 10 silver...! 

This is dangerous when autobuy is on for vendor-profit.

The work around i have found is to add "/and/not/tooltip/charges" to the autobuy search so that it ignores all those items alltogether.

I thought you could be interested in this bug. 

**-Any way onto the second issue. (Weird issue)**

I have been using Real Time scan regurally but for a whole day the function was not working. The addon was not scanning the last page for some reason, it was scanning the same page over and over. The next day everything worked again and since that day i haven't have a problem with real time. I have literally no idea why this didn't work for only one day and it is working great after and before that day as well :O
You could say it was because nothing was being posted but in fact it was the exact opposite. It was a Saturday which typically people are posting like crazy server had over 10k online so that's definitely not the case. Maybe even the problem appeared because so many auctions were being posted that Real time could not keep up?! No idea seriously.

**I will close this with a suggestion!**

I really think that the addon does a very good job overall but i think the Historical Price you are using (Mean of minimum of the last 10 days) is not ideal for trade goods, or any item that is being posted by large volume daily (mostly trade goods). The Historical price is working great for equipment and all other auctions.

Let me explain.

The nature of trade goods and the large volume of them lead to many people posting their shit. There is always that guy that will post his copper ore for 50c each even tho the whole server sells it for 2.5s ea. Ofc i can buy the cheap ore and flip it for a profit, no problem! but that happens daily and the Historical Price is being calculated by that guy that goes and posts his ore/leather/herbs super cheap. 

The result?! A typical seach for any herb/leather/ore is showing 300% minimum and the value of the item is very low compared to the REAL value. Copper ore for example has a historical value of 1.06 while everything under 2.6s sells INSTANTLY. That is being caused by the low price outliers that happen DAILY for trade goods. So for every ore/cloth/herb/leather etc the % of Hist. Value is always red and usually between 200% and 300%.

How to fix this? For high volume items like trade goods use another formula for the daily Historical price. That should fix the problem with the item value that is calculated over the last 10 days. So the daily price could be the average of the 10(or even 15) cheapest auctions that were encountered that day. So for example if one guy decide to sell his copper ore at 50c instead of 2.5s ea that will not mess up the whole daily value and also the long term value of the item. 

Here i have to repeat for equipment and other stuff the current Historical Price is **PERFECT**. It gives you a very good idea of the value of a blue BoE or some other equipment! The only problem is with trade goods and items that are generally over 20-30 of them up for sale at any given time. 

That was all i had observed over the last month using your addon.
Feel free to ask any questions or clarifications if i wasn't clear enough. 
I'm happy to help you in any way!

Cheers and thanks for this great addon!

**Comment by theoden-dd** [comment]
My little proposal aside is to count daily price for trade goods not as

> the average of the 10(or even 15) cheapest auctions

but as the _median_ of the 15 _different_ cheapest auctions. Just to be more specific.

This would protect from that guy with 20 auctions of 1 copper ore for 50c.
What do you think, guys?

**Comment by theoden-dd** [comment]
And sorry for the off topic. @drtakhs , how to turn on the Real Time search?

Couldn't find it neither in the readme nor in the interface.

@shirsig Should I create a separate issue for this question?

**Comment by drtakhs** [comment]
@theoden-dd look at the very top left of the aux window where it says range. click it and it becomes realtime. For example if you search for copper ore and you are on realtime mode, only the last page of copper ores will be searched. and it will continue to scan the last page after that on repeat

**Comment by drtakhs** [comment]
@theoden-dd yeah i thought that about the different auctions, it makes perfect sense, but i don't think that it's possible with the vanilla API, that's why i said 10-15 cheapest...  i think mean of cheapest is the best we can get atm, but i am not quite sure. Ideally what you said is the best solution, but that would mean that you will have to mess with Seller Names, time, and other stuff in order to decide what a "different" auction is...

**Comment by theoden-dd** [comment]
Saying "different" I meant another conjunction of bid/buyout prices per item. Seller doesn't matter.

Actually, aux already does almost the same grouping on the post tab, when counting "auctions" column. However it takes into account stack size there. It's not needed for the discussed calculation.

**Comment by shirsig** [comment]
Charges being shown as stack size in the listing is intended. The vendor price tooltip entry showing the unit price (per charge) is also intended.

>So i noticed this strange behaviour when auto-buy bought the [Discombulator Ray] item thinking that i would make a vendor profit! The addon calculated the vendor price to be 5x10s instead of 10 silver...!

I don't understand. If the vendor price is correctly 2s like you wrote above then you would get 5x2s = 10s

@drtakhs @theoden-dd 
The daily price is not an average of anything, it is simply the min price of the day, thus solves the problem you mention. I guess it tends to be a bit too low but for the historical price which is a median of daily prices that doesn't seem to matter much.

**Comment by drtakhs** [comment]
> So i noticed this strange behaviour when auto-buy bought the [Discombulator Ray] item thinking that i would make a vendor profit! The addon calculated the vendor price to be 5x10s instead of 10 silver...!

> Charges being shown as stack size in the listing is intended. The vendor price tooltip entry showing the unit price (per charge) is also intended.

> I don't understand. If the vendor price is correctly 2s like you wrote above then you would get 5x2s = 10s

The whole thing is confusing and doesn't really make sense, to me at least. An item with charges is still ONE ITEM. Charges being shown as stack size causes problems. The addon shows the [Discombulator Ray] costing 45s on vendor-profit scan because it thinks the vendor price is 5x10. This is clearly a bug, The item sells at the vendor for 10s.

The fact that charges are being shown as stack size creates problems when posting an item as well take a look at these photos.

![wowscrnshot_022617_230826](https://cloud.githubusercontent.com/assets/15212862/23345149/cf6af5ae-fc91-11e6-9e9d-153143b020aa.jpg)

![wowscrnshot_022617_230835](https://cloud.githubusercontent.com/assets/15212862/23345152/d438476c-fc91-11e6-8cc9-145ec4474a89.jpg)

**Comment by shirsig** [comment]
It's not really complicated. Charges are mostly treated the same as stacks. It makes sense to adjust the stack size because you may have items with different amounts of charges and they should be priced by charge. That the stacks are fixed doesn't matter because aux will consider that for the stack-counts it allows. If there's a problem with the vendor profit scan it's because you have an error in your vendor price database. (like, this was bugged in an early aux_merchant_prices, but aux itself should always have corrected it when visiting a vendor) It is in fact necessary to use per-charge pricing for vendor profit because the vendor price also depends on the charges.

**Comment by drtakhs** [comment]
Alright i see now, thanks for clarification!
