### ISSUE TITLE
Post Duration not saving after last updates 

### ISSUE THREAD

**Issue by Haroldyolo** [shirsig/aux-addon#82]
Just re-downloaded aux today with the recent updates and the post duration is not saving. I have to manually click it every time. Is that intended or a bug?

**Comment by shirsig** [comment]
you have to delete the savedvariables

**Comment by Haroldyolo** [comment]
Which Savedvariables exacty? There are several in teh WTF folder?

**Comment by shirsig** [comment]
the account wide ones

**Comment by Haroldyolo** [comment]
Sorry this still does't make sense still. 

Do you mean the one in: 

WTF\Account\nameofaccount\SavedVariables.lua folder or

the one in WTF\Account\nameofaccount\SavedVariables\aux-addon.lua

And wouldn't that delete all the history of aux as well?

**Comment by shirsig** [comment]
you can delete them all and yes

**Comment by Haroldyolo** [comment]
Any way to keep the data and just change the duration inside the file only somehow? I don't wanna loose all the scans and history etc

**Comment by Haroldyolo** [comment]
Problem solved. For future reference we don't have to delete every single one. Just this one: WTF\Account\nameofaccount\SavedVariables.lua
