### ISSUE TITLE
Item's not found in the Post window

### ISSUE THREAD

**Issue by Haroldyolo** [shirsig/aux-addon#83]
Hey,

Tried to sell few things this morning, but once I click on them in the post window it finds 0 items of that kind, but if I go and search for it in the search window it appears.Pretty sure that is a bug with the post screen or something. Happens with green items mostly, one example is shield I have called: Robust Buckler of the Falcon

Thanks.

**Comment by shirsig** [comment]
I think the post window treats different suffixes as different items. Makes sense because the suffix can have a huge impact on the value. For example, 4/4 scouting gloves of the monkey is a valuable twink item which may sell for 100g, 3/3 scouting gloves of the owl is worth no more than its vendor price.

**Comment by Haroldyolo** [comment]
Am I understanding this correctly...if the post window evaluate suffix to be garbage it won't show it at all in the results? I thought all the post window does is scan all the auctions for the current item (exact item, suffix and prefixes) and then display it.

**Comment by shirsig** [comment]
Yeah that's what it does. The search tab on the other hand does not consider the suffix unless you use a tooltip filter so that's why you'll see items there that you don't see in the post tab.

**Comment by shirsig** [comment]
Note that there are different suffixes with the same name. E.g., Scouting gloves of the monkey exist as 4/4, 4/3, 3/4, and 3/3.

**Comment by Haroldyolo** [comment]
Oh that makes more sense now yeah. I always thought for some reason that each suffix is constant value, but if they are float then it's understandable for the garbage ones not to be even considered for posting.

**Comment by shirsig** [comment]
No, everything is considered for posting, but only if it's exactly the same suffix.
