### ISSUE TITLE
Scan for undercut auctions option

### ISSUE THREAD

**Issue by Haroldyolo** [shirsig/aux-addon#84]
Hey.

I am sure you are familiar with the TSM option where you can scan your posted auctions to see if you are been undercut. Is that something that could be implemented into aux or how complicated it is? I have good knowledge of python, but none in lua so if there is anything I can help with please let me know.

Thanks.

**Comment by drtakhs** [comment]
nice suggestion +1

**Comment by shirsig** [comment]
It's possible in principle. The problem with all scanning features is just that scans are so much slower in vanilla than retail, making indiscriminate scans rather impractical. What you already can do is right-click a specific auction in the listing to make a search in the search tab. I think this should be enough for 99% of users if they even bother with this at all, so I don't think it's worth the complication of the interface.
