### ISSUE TITLE
Unable to post equipment

### ISSUE THREAD

**Issue by DaK1Ga** [shirsig/aux-addon#85]
Hi,

I've experienced an issue regarding posting of equipment. As far as I can tell, it does not occur on any other item, except equipment. Tried to sell Spider Silk Boots (1 in bag), doesnt work, not even able to change price. But it automatically hides this item for no reason. Same happend with shoulder pads, had several in bags. At first thought it's due too many in my bags but even if I placed every other on bank it doesnt change anything.

Facing this issue since latest update. (Since there is no longer a distinct bid price tab)

This is great work, keep it up!

Best wishes,

Daniel

**Comment by shirsig** [comment]
Hey
Probably because of the incompatible saved settings. Try deleting the
savedvariables.
Regards, Simon

**Comment by DaK1Ga** [comment]
Hi,

thanks for pointing this out, sometimes the solution is way easier than thought.

Issue resolved!
