### ISSUE TITLE
*Post* search finds nothing for items with suffix

### ISSUE THREAD

**Issue by theoden-dd** [shirsig/aux-addon#86]
Couple of screen shots to explain:

![wowscrnshot_021517_200223](https://cloud.githubusercontent.com/assets/2167281/23090996/8f0718a2-f5bc-11e6-8ffb-6decae8765d9.png)
![wowscrnshot_021517_200242](https://cloud.githubusercontent.com/assets/2167281/23091023/467229d2-f5bd-11e6-9082-69b5e9ab75c6.png)

Ofc, screen shots were made with a minimal lag. So the auction from the first one was no doubt still in the market.

I've confirmed it with some other suffix items, so any of them should work as a reproducer.

**Comment by Haroldyolo** [comment]
This happens, because the suffix had different value. Your boots are 3spirit and 2stamina and the other one are/were different. The addon is matching the items perfectly a.k.a to the exact value of a suffix

**Comment by theoden-dd** [comment]
The suffixes are perfectly the same here: "...of the Whale".

Do you mean, it compares bonuses amount?

**Comment by Haroldyolo** [comment]
Yes it matches the number or whatever you wanna call it, value,amount, of the suffix. in your case of the whale could be anything between 1 and 9 i believe

**Comment by drtakhs** [comment]
he is correct probably the item that you saw on sale was +3 spirit +3 stamina

**Comment by theoden-dd** [comment]
Sorry for a big delay. Up to now I've got no more reproducers, but the explanation upper is right.

Additional evidence: #83
