### ISSUE TITLE
Right click an item while on Auctions and Bids tabs

### ISSUE THREAD

**Issue by sipertruk** [shirsig/aux-addon#88]
The simple right click being the way to search/auction an item, accidental use of items (flasks!)  can happens while being on Auctions and Bids tabs if we forget to select the other tabs first.
Suggestion : the right click should be handled on all tabs to avoid this.

**Comment by shirsig** [comment]
I kinda would like to just have it search on all tabs, though it seems some people really dislike the post listing and prefer to use the inventory so I guess I'll leave that.

Making the post tab an exception is kinda weird though so I simply disabled it on the other 2 tabs for lack of a better idea of what to use it for.

Note that modified clicks (alt/ctrl/shift) still go through (on all tabs).
