### ISSUE TITLE
Real Time mode keeps showing the same results

### ISSUE THREAD

**Issue by raine** [shirsig/aux-addon#89]
For a few hours now, with `<>` as the query, Real Time mode has been showing pretty much the same results. 

I can't say with certainty that it has worked perfectly before, but someone seems to have had similar issue in #81.

Also, if you need any help debugging this let me know. I see that some of the real time search logic is in `tabs/search/results.lua`.

**Comment by drtakhs** [comment]
i can confirm this as well, for the past 3 days real time search is scanning the same stuff over and over :/

**Comment by Haroldyolo** [comment]
Tested and confirmed here too. Real Time is bugged.

**Comment by shirsig** [comment]
not an aux bug, the ah sorting is wrong on elysium/kronos

**Comment by mooreatv** [comment]
is it know to be broken on lightshope too ? because it's the same items show up there too in realtime mode (in full scan there is a bit over 600 pages)

**Comment by shirsig** [comment]
Dont know but u can easily check. The blizzlike sorting is the oldest auctions are on the first page so if u find auctions with long time left on the first pages then most likely they broke the sorting to prevent sniping or for whatever reason.
