### ISSUE TITLE
LUA error - after updating file from github

### ISSUE THREAD

**Issue by filbo88** [shirsig/aux-addon#90]
So I had acquired the Aux-addon from another vanilla add-on site. It worked just fine.

I tried changing my auction house add-on to Auctioneer. Found that I didn't like Auctioneer as much as Aux. Deleated Auctioneer and re-added Aux to my \Interface\AddOns 

Since then I cannot use Aux in game and I get the attached error:
![img_0536](https://cloud.githubusercontent.com/assets/25888646/23108083/9d209d90-f6d5-11e6-9c9c-1f38f2f7659d.JPG)

Any advice on how to fix this error? I have tried removing and re-adding AUX. I am using the aux-addon-master from this github.

Thanks

**Comment by Haroldyolo** [comment]
Delete everything related to Aux in your WTF folder.

**Comment by filbo88** [comment]
I'll give that a try

**Comment by filbo88** [comment]
IT WORKED!! Thank you!! Note: I also went through and deleted the info from all my toons.
