### ISSUE TITLE
Click in bid table on post tab processes stacks badly

### ISSUE THREAD

**Issue by theoden-dd** [shirsig/aux-addon#92]
1. When clicking in the bid table on the post tab to set *unit* bid as in the table,
aux sets it to the unit_bid_from_table * table_stack_size.
2. Bid table coloring is broken too. It colors in red auctions where *stack* bid is lower than entered *unit* bid.

On the screenshot I'd just clicked on the selected row:
![wowscrnshot_021917_093909](https://cloud.githubusercontent.com/assets/2167281/23275365/5005ba6e-fa17-11e6-8d29-e36a9f1b90e3.png)

**Comment by shirsig** [comment]
this is intended. the point of bid undercutting is to have a lower stack price so you appear higher up in the default auction house.

**Comment by shirsig** [comment]
actually you may have an old version that works differently

**Comment by theoden-dd** [comment]
I'm using ac9d6ffca827d21ca58c854ee8df4f4c06761f0b
