### ISSUE TITLE
vendor-profit/1c bug due to rounding

### ISSUE THREAD

**Issue by theoden-dd** [shirsig/aux-addon#97]
On the screenshot item price = 999c/20 = 49,95c
Vendor-profit = 50c - 49,95c = 0,05c which is **less** than 1c.

In the item price column there is a value 50c, rounded up to whole number. This amazes even more.
Why don't you add at least single decimal digit in that column? Two decimal digits would be even better.
![wowscrnshot_030517_100459](https://cloud.githubusercontent.com/assets/2167281/23588269/122a0436-01cc-11e7-9731-a2868c6b1879.png)

**Comment by shirsig** [comment]
The vendor profit is calculated by auction, not by unit. I guess the reasoning was that the work you have to do (buying out, emptying the mailbox, vendoring) is proportional to the number of auctions, not units, but there may also be advantages of calculating it by unit, I'm not sure ...

Anyway, this is the reason for your result. 9.99s buyout, 20*50c = 10s vendor -> 1c profit

**Comment by theoden-dd** [comment]
Had no chance to think about stacks, that's so unusual.
Thank you for the explanation.
