### ISSUE TITLE
Post tab bid display

### ISSUE THREAD

**Issue by drtakhs** [shirsig/aux-addon#98]
![asdasdas](https://cloud.githubusercontent.com/assets/15212862/23725262/9336a96a-0458-11e7-9530-d413319aa394.jpg)

This is a strange one, bid prices are obviously wrong. All of them are different from the true bid price that you see when you search the AH normally, some other items don't have this problem.

**Comment by shirsig** [comment]
It doesn't show the actual unit bids, it shows the bids divided by your selected stack size. The listing is meant to help undercut stack bid prices to appear high up in the default AH.

**Comment by drtakhs** [comment]
You are correct, but prices act strange, am i missing something?

Some more screenshots highlighting strange behaviour

![dfs](https://cloud.githubusercontent.com/assets/15212862/23725537/b31a4132-0459-11e7-97d4-b4a0d4ed4cb7.jpg)


![asdasdasdasdas](https://cloud.githubusercontent.com/assets/15212862/23725545/b6385322-0459-11e7-9d66-17a4fefb9b49.jpg)

Sorry if i dont understand something

**Comment by shirsig** [comment]
What's strange. Like i just said, they're divided by your selected stack size. (2 in this case)

**Comment by drtakhs** [comment]
Check the 2 last auctions on the last picture, the bids are 59.84 & 59.86 accordingly and the stack size of both auctions is one. Now look at the second-last picture. why when i choose stack size 2 do 59.84 & 59.86 get divided by two? what's the meaning of 29.92 & 29.93 ?

**Comment by shirsig** [comment]
It has no meaning beyond being "the stack price divided by your selected stack size"
I just think it's the most useful value to show with regard to undercutting the stack price.

**Comment by drtakhs** [comment]
oh okay, i see :)
